ReactionMechanismGenerator/RMG-database

- input/solvation/groups/abraham.py
- input/solvation/groups/radical.py
These values correct the Abraham 'A' values for radicals that had been saturated with H's when looking up the solvation. Goes along with pull request https://github.com/GreenGroup/RMG-Py/pull/364 in RMG-Py
> Radical solvation thermo groups

- input/solvation/groups/abraham.py
This pull request addresses https://github.com/GreenGroup/RMG-Py/issues/367 and goes along with pull request https://github.com/GreenGroup/RMG-Py/pull/378
The values for these groups are the same as for CdH2 and Od, respectively. This makes it so that the value of the solute descriptors for resonance isomers for carbon monoxide are the same. They are not "real" Platts groups and there is still no Platts group for Ot bonded to anything besides Ct. This way we still catch when there are no Platts groups for something RMG encounters.
> Added solvation thermo groups for CtOt and OtCt.

- input/kinetics/families/intra_substitutionCS_isomerization/groups.py
Closes https://github.com/GreenGroup/RMG-Py/issues/382
Also must reorder the tree since the rules are listed
in terms of templates that go
XSRJ;C;YJ
The tree must also obey this order in order for kinetics
to be determined correctly.
We should probably have a database test for this.
> intra_substitutionCS_isomerization should not be its own reverse

- input/kinetics/families/1,2_shiftS/groups.py
- input/kinetics/families/H_Abstraction/rules.py
Addresses and closes https://github.com/GreenGroup/RMG-database/issues/65 in conjunction with new database unit tests in https://github.com/GreenGroup/RMG-Py/commit/5151e4cadaecbb78685a8adc107cde1edd466422
- Makes sure that reaction template in family is declared with nonidentical reactant and product names if the family is not its own reverse, so that no groups get overwritten.
- Changes the ordering of groups in rules to match that of the tree's order.
> Database fixes corresponding to new unit tests

- input/thermo/groups/ring.py
GAV's derived from just the molecules themselves which I found in the
DFT_QCI library. Adding the GAV values makes it so that substituted
molecules will be much more accurate during model generation.
Admittedly the method for deriving the GAV is not great because of the
minimal training set, but it will probably still be much better than it
was.
> Add GAV for oxitene and oxerene ring groups

- scripts/importChemkinLibrary.py
Turn on markDuplicates when checking for duplicate reactions.
Chemkin allows mixed pdep/non-pdep duplicates without duplicate flag,
but RMG requires them to be marked.
> Enable markDuplicates for importChemkinLibrary

- input/kinetics/families/R_Addition_MultipleBond/rules.py
- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
This PR adds some of the content of Table 4 of Wang et al (2015) in the form of
* 6 training reactions
* 4 rate rules
The rates pertain to the addition of allyl radical to double bonds in ethene, propene, and butene-like compounds, and are based on CBS-QB3 estimates.
Although, the newly added tree nodes already existed, they were now given a higher rank the already existing rate rules, as I believe they are more accurate.
> Wang et al (2015) allyl additions to double bonds

- input/kinetics/families/2+2_cycloaddition_Cd/groups.py
- input/kinetics/families/Diels_alder_addition/groups.py
- input/kinetics/families/R_Addition_MultipleBond/groups.py
This PR added several aromatic groups to forbidden groups of two families
- Diels_Alder_Addition: e.g., benzene cannot serve as a diene 
- R_Addition_MultipleBond
- 2+2_cycloaddition_Cd
> Add aromatic forbidden groups to Diels_Alder_Addition, R_Addition_MultipleBond, and 2+2_cycloaddition_Cd

- input/kinetics/families/H_Abstraction/rules.py
We reference the Curran paper, but they got the rate from the Walker publication.
Refer to original pull request: https://github.com/ReactionMechanismGenerator/RMG-database/pull/88
This is mainly just to test if travis build triggers properly again.
> Update reference for H_abstraction rule 'C/H3/Cs;O_rad/NonDeO'

- input/kinetics/families/Diels_alder_addition/groups.py
- input/kinetics/families/H_shift_cyclopentadiene/training/dictionary.txt
- input/kinetics/families/H_shift_cyclopentadiene/training/reactions.py
- input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
- input/kinetics/families/Intra_R_Add_Exocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Exocyclic/training/reactions.py
- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- input/kinetics/families/R_Recombination/training/dictionary.txt
- input/kinetics/families/R_Recombination/training/reactions.py
- input/kinetics/families/intra_H_migration/training/dictionary.txt
- input/kinetics/families/intra_H_migration/training/reactions.py
- input/thermo/groups/polycyclic.py
- input/thermo/groups/ring.py
- Prevent benzyl radicals from reacting in diels alder reaction family.
- Add a series of new polycyclic thermo group corrections derived from Aaron and Shamel's libraries
- Add aromatic and benzene ring groups with zero value to complement Cb bond corrections
- Give ranks to generic nodes (rank = 10 indicating very bad estimate) and aromatic nodes (rank = 1 so that RMG prioritizes it) so that they can be sorted in the thermo estimation algorithm in RMG-Py
- Training reactions from Aaron and shamel's libraries
> Cyclic database improvements

- .gitignore
- scripts/convertKineticsLibraryToTrainingReactions.ipynb
- scripts/fitPolycyclicThermoGroupsFromThermoLibrary.ipynb
- scripts/showNewTrainingRxnsImprovements.ipynb
Add ipython notebook scripts for:
- fitting polycyclic thermo groups from a thermo library
- adding training reactions from a kinetics library
These scripts are interactive and also show debugging data.
> Training reactions and polycyclic thermo scripts

- .travis.yml
- deploy.sh
This PR implements the [same solution as for RMG-Py](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/625) to deal with pull requests from users external of the RMG organization.
In summary: their PR's will not trigger a RMG-tests rebuild, but they won't crash the current travis build neither.
> move deploy key decryption into deploy.sh

- .travis.yml
This PR fixes the outdated miniconda URL and updates `.travis.yaml` file the repository.
> fix anaconda in .travis yaml

- input/kinetics/families/H_Abstraction/groups.py
The Y_2centeradjbirad node is a child of Y_rad and is captured 
by the very generic Y_rad definition. Having it appear
at the start of the OR{} definition for the top-level 
Y_rad_birad_trirad_quadrad seems thus redundant, confusing,
and slower??
> More concise top-level definition of Y. in H_Abstraction.

- input/thermo/groups/ring.py
This fixes one mistake in the database after changing the matchNodeToChild to check atom labels. Luckily there were no other errors found.
> Add star to fix bug with parent/child to rings.py

- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
I got assigned to add these rates a while ago but never got around to pushing them...
These are rates computed at the CBS-QB3 level of theory, from a 2015 paper by Wang, Villano, and Dean (http://pubs.acs.org/doi/abs/10.1021/jp511017z).
I added some nodes to the tree to prevent some of the rates from falling to the same node. However, I don't know if they way I added them are computationally or chemically optimal. Someone else should definitely review them before merging.
> More Intra_R_Add_Endocyclic training rates

- input/statmech/groups/groups.py
In statmech groups.py I changed the frequencies of the Nitro (R-NO2) group. This group was originally assigned 6 frequencies, while it is only allowed a maximum of 5 (see https://dspace.mit.edu/handle/1721.1/59876). The weakest frequency range of 1545-1555 1/cm was hence removed.
> Changed frequencies of the Nitro group (statmech groups.py)

- .gitignore
- input/kinetics/families/Intra_R_Add_Endocyclic/NIST/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/NIST/reactions.py
- input/kinetics/families/intra_H_migration/NIST/dictionary.txt
- input/kinetics/families/ketoenol/NIST/reactions.py
- testing/evaluateKinetics.py
This is a revised and updated script of Nathan's old kinetics evaluation script containing 3 main functionalities: 
- `obtainKineticsFamilyStatistics`: gathers and saves data about families into a .csv files containing info on the number of **exact** rate rules, number of groups per tree in the groups
- `leaveOneOut`: performs a leave one out test by deleting an **exact** node (excludes averaged ones), averaging the tree and then trying to estimate that tree.  Creates parity plots for each family and creates a .csv of the root mean square error.
- `compareNIST`: compares the family estimated kinetics against the exact kinetics from the NIST depository within each family.  Also creates parity plots and .csv of error data.
> Add evaluateKinetics.py script to testing folder

- input/kinetics/families/Disproportionation/rules.py
- input/kinetics/families/R_Recombination/rules.py
Found bug after getting Ea = -50, causing system to
be too stiff and crash.  We found that the alpha and n
kinetics values in Disproportionation were switched
due to a typo. The form of the kinetics should not be
Evans-Polanyi.  We also found that the MRH comments in the
kinetics descriptions are no longer relevant as it
corresponds to a previous version of the rate rule.
The rate rule in the database was constructed by
AG Vandeputte.
> Delete comments and fix typo in Srad Disproportionation and R_Recombination rate rules

- input/kinetics/families/Korcek_step2/groups.py
- input/kinetics/families/Korcek_step2/rules.py
- input/kinetics/families/R_Addition_COm/groups.py
- input/kinetics/families/R_Addition_COm/rules.py
- input/kinetics/families/R_Addition_CSm/groups.py
- testing/databaseTest.py
We will now be using square brackets in comments describing kinetics. Banning them in group labels will make them easier to parse.
> Ban square brackets in kinetics group names

- input/thermo/groups/polycyclic.py
- testing/databaseTest.py
Previously sibling and parent checking is deactivated for polycyclics because we don't want some siblings in polycyclics to be parent-children relationship although structure-wise they are parent-children. For instance, tricyclics have more specific structures than bicyclics so current sibling parent testing will complain that tricyclics should be under bicyclics, however we don't want using tricyclics ring strains to average for bicyclics ring strains. It's more chemically more sensible to have tricyclics and bicyclics as siblings. For current testing, we should place tricyclics before bicyclics to avoid failure of sibling parent testing. This PR reorganize the tree a bit to achieve that.
> Make polycyclic pass sibling parent testing

- .travis.yml
- input/solvation/groups/abraham.py
- input/solvation/groups/nonacentered.py
- input/statmech/groups/groups.py
- input/thermo/groups/group.py
- input/thermo/groups/polycyclic.py
- input/thermo/groups/radical.py
- testing/databaseTest.py
This pull request fixes accessibility issues in the database. 
For various reasons, sometimes an entry in a tree will not be descended to properly. I have created a unit test to make a sample molecule and attempt to descend the tree. All fixes from this commit was found with this unit test.
> Entry acessibility

- input/kinetics/libraries/FFCM1(-)/dictionary.txt
- input/kinetics/libraries/FFCM1(-)/reactions.py
- input/thermo/libraries/FFCM1(-).py
This PR includes the kinetics + thermo libraries of the Foundational Fuel Chemistry Model Version 1.0
Note: Excited species (OH, CH, CH2) were removed.
Also, thermo data of species not in this mechanism were commented out.
http://web.stanford.edu/group/haiwanglab/FFCM1/pages/FFCM1.html
> Added the FFCM-1 library (kinetic + thermo)

- input/thermo/groups/group.py
It is difficult to make sample molecules for groups with too many implicit Cbf atoms, so for now we force everything with >3 Cbf atoms to be fully explicit on its benzene rings.
> Make Cbf-CbfCbfCbf group fully explicit

- input/kinetics/libraries/kislovB/reactions.py
Added the following 3 reactions on the phenyl + propargyl surface to the kislovB kinetic library:
1. Phenyl + propargyl = stable adduct (includes addition to either end of propargyl)
2. Indenyl + H = Indene (exit channel)
All 3 reactions are barrierless and are therefore assumed to be in the collision limit
> Added kinetics for entrance and exit channels of phenyl + propargyl surface in kislovB library

- scripts/exportKineticsLibraryToChemkin.py
Currently run this script results in an AttributeError: 
`AttributeError: 'Species' object has no attribute 'generateThermoData'`
Because we don't have the method species.generateThermoData() any more.
Replace this method with species.getThermoData() should fix this error.
> Fix the script exportKineticsLibraryToChemkin

- .travis.yml
Previously we always use the latest miniconda, but occasionally it breaks travis, we'd like to use stable version instead to give stable travis performance.
> change miniconda to stable version

- input/kinetics/libraries/1989_Stewart_2CH3_to_C2H5_H/dictionary.txt
- input/kinetics/libraries/1989_Stewart_2CH3_to_C2H5_H/reactions.py
- input/kinetics/libraries/2005_Senosiain_OH_C2H2/dictionary.txt
- input/kinetics/libraries/2005_Senosiain_OH_C2H2/reactions.py
- input/kinetics/libraries/2006_Joshi_OH_CO/dictionary.txt
- input/kinetics/libraries/2006_Joshi_OH_CO/reactions.py
Added P-dependent kinetic libraries for the 3 following small molecule surfaces:
1. 2CH3 = C2H5 + H from 1989 Stewart calculations
2. OH + C2H2 from 2005 Senosiain calculations
3. OH + CO from 2006 Joshi calculations
The comments in each library indicate for which bath gas the calculations were done ("strong collider" for 1, and Ar/N2 for 2 and 3). For most combustion relevant conditions the P-dep of these reactions are negligible, so for most RMG jobs these libraries will not be much of an improvement over FFCM, which includes all of the above reactions without P-dep.
> Added P-dependent kinetic libraries for 3 small molecule surfaces

- scripts/exportKineticsLibraryToChemkin.py
- scripts/importChemkinLibrary.py
Modified exportKineticsLibrarytoChemkin.py and importChemkinLibrary.py scripts to print out the corresponding reaction library for each reaction
in the chem.inp Chemkin input file (as a comment for each reaction entry) in the first case (export), and
in the reactions.py library (as the "long_desc") for the second case (import).
> Modified exportKineticsLibrarytoChemkin.py and importChemkinLibrary.py

- input/thermo/libraries/NitrogenCurran.py
This thermo library covers 52 species,
many of which are important in the formation and consumption chemistry
of NOx species in combustion. Calculated at the B3LYP/cc-pVTZ level of theory.
Since RMG does not distinguish between cis\trans conformers, a representative
conformer was chosen based on lower heat of formation.
> Added the NitrogenCurran thermo library

- input/kinetics/families/Disproportionation/groups.py
H_rad is child of Y_rad, so it should not be listed in the top logic node. Also move H_rad higher in the tree since it's a common radical.
H_rad was added to the logic node in 155821c2f94973f511fe9a9c71003349148d213b, probably by accident, It is still listed as a child of Y_rad in the tree structure.
Addresses #158.
> Fix bug in disproportionation tree

- input/kinetics/families/1,2_shiftS/groups.py
- input/kinetics/families/Birad_recombination/groups.py
- input/kinetics/families/Cyclic_Ether_Formation/groups.py
- input/kinetics/families/Cyclic_Ether_Formation/groups_OLD.py
- input/kinetics/families/Cyclic_Ether_Formation/rules.py
- input/kinetics/families/Cyclic_Ether_Formation/rules_old.py
- input/kinetics/families/Intra_Disproportionation/groups.py
- input/kinetics/families/Intra_RH_Add_Endocyclic/groups.py
- input/kinetics/families/Intra_RH_Add_Exocyclic/groups.py
- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/families/Intra_R_Add_ExoTetCyclic/groups.py
- input/kinetics/families/Intra_R_Add_Exocyclic/groups.py
- input/kinetics/families/intra_H_migration/groups.py
- input/kinetics/families/intra_H_migration/groupsTest.py
- input/kinetics/families/intra_H_migration/rules.py
- input/kinetics/families/intra_H_migration/rulesTest.py
- input/kinetics/families/intra_OH_migration/groups.py
- input/kinetics/families/intra_substitutionCS_cyclization/groups.py
- input/kinetics/families/intra_substitutionCS_isomerization/groups.py
- input/kinetics/families/intra_substitutionS_cyclization/groups.py
- input/kinetics/families/intra_substitutionS_isomerization/groups.py
- input/kinetics/families/ketoenol/groups.py
- input/kinetics/families/ketoenol/rules.py
Unimolecular Group formatting changes and testing.
A new test requires that end group labels are consistent throughout each end group tree, that the backbone has all labels present in the end groups and labels indicating the shortest path between end groups, and that each end group subgraph in each entry in the backbone tree is the top level of the corresponding end group tree.
Specifically exempts Diels_alder_addition family from these requirements because of its strange structure (to be fixed later)
Groups were adapted to meet these requirements and pass all database tests. Part2 includes the problematic families that need more thorough review of the RMG-tests.
> Unimol kinetics part2

- input/kinetics/libraries/FFCM1(-)/dictionary.txt
- input/kinetics/libraries/FFCM1(-)/reactions.py
- input/thermo/libraries/FFCM1(-).py
This PR includes some modifications to the FFCM library for better representation of the different multiplicities:
- C radical was changed from multiplicity 5 to 3, and is now explicitly called C(T)
- Both forms of the CH radical are now included, CH(D) and CH(Q), along with thermo data
- CH2 radicals are now explicitly called either CH2(S) or CH2(T). [previously was CH2 and CH2(S)]
- Reactions involving the excited CH state, CH(T), were added
- All reactions are now reversible
- The excited state of OH radicals was not added yet (commented-out)
related to #171 and #172 
This should not be merged yet. We should first see if the different excitation states coincide with our rate rules, and whether this is the approach we'd like to take.
> Improve excited species handeling in FFCM1(-)

- input/kinetics/libraries/JetSurF2.0/dictionary.txt
- input/kinetics/libraries/JetSurF2.0/reactions.py
- input/thermo/libraries/JetSurF2.0.py
Originally I mistakenly named these libraries with the suffix `0.2`, where in fact they are version `2.0`.
The libraries names were corrected now as well.
Main changes in this commit are:
- The AdjLists of [C] were corrected to a multiplicity 3 instead of 5 (see issue #171)
- The AdjLists of [CH] were corrected to a multiplicity 2 instead of 4 (see issue #172)
- The representations of CH2 and CH2(S) were correct and weren't changed
- Reactions of `[CH]*` and `[OH]*` (which currently cannot be represented in RMG) were added as a comment
> The JetSurF libraries were corrected for [C], [CH], [CH2], [OH]

- input/kinetics/libraries/FFCM1(-)/dictionary.txt
- input/kinetics/libraries/FFCM1(-)/reactions.py
- input/thermo/libraries/FFCM1(-).py
The reactions involving `[CH]*` were removed, since the `CH(Q)` representation was wrong,
and currently we cannot represent `[CH]*` uniquely in RMG.
These reactions were added at the top of the library as a comment.
An explanatory comment was added for users who would like to have `[CH]*` and [OH]* in their models.
The `CH(D)` name was also replaced to simply `CH`,
not to cause a false impression that the excited state is other than a doublet as well.
See issue #174
> The FFCM library was changed with respect to `[CH]*`

- input/thermo/libraries/FFCM1(-).py
The FFCM-1 project report thermo data for species which do not participate in any of its reactions. Originally this data was commented-out in our thermo FFCM1(-) library.
It is now brought back to life. The species are:
HOCO, CH3O2, CH3O2H, C2H5OH, CH3OCH3, CH2CH2OH, CH3CHOH,
CH3CH2O,CH3OCH2, CH2OCH2, C2H3OH, C2H3O, HCCOH, C2O
Also, the AdjList for CH3CHO was corrected.
> Added species to FFCM-1 thermo:

- input/kinetics/families/R_Addition_MultipleBond/rules.py
This PR will include all changes needed to make transition of [CH] groundstate from quartet to the more correct doublet version. This is what currently what we have (the list will be extended as we make more changes):
- kinetic rules: R_Addition_MB rxn#3202 (this PR)
- kinetic libraries: 
- FFCM (PR #177 )
- JetSurf (PR #178)
- thermo groups: None
- thermo libraries:
- FFCM (PR #177 )
- JetSurf (PR #178)
> Database modifications for better [C], [CH], [CH2], [OH] electric state consistency

- input/kinetics/libraries/Dooley/C1/dictionary.txt
- input/kinetics/libraries/Dooley/methylformate/dictionary.txt
- input/kinetics/libraries/Dooley/methylformate_all_ARHEbathgas/dictionary.txt
- input/kinetics/libraries/Dooley/methylformate_all_N2bathgas/dictionary.txt
- input/kinetics/libraries/ERC-FoundationFuelv0.9/dictionary.txt
- input/kinetics/libraries/ERC-FoundationFuelv0.9/reactions.py
- input/kinetics/libraries/GRI-Mech3.0-N/dictionary.txt
- input/kinetics/libraries/GRI-Mech3.0/dictionary.txt
- input/kinetics/libraries/GRI-Mech3.0/reactions.py
- input/kinetics/libraries/Nitrogen_Dean_and_Bozzelli/dictionary.txt
- input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/dictionary.txt
- input/kinetics/libraries/Nitrogen_Glarborg_Zhang_et_al/dictionary.txt
- input/kinetics/libraries/combustion_core/version2/dictionary.txt
- input/kinetics/libraries/combustion_core/version2/reactions.py
- input/kinetics/libraries/combustion_core/version3/dictionary.txt
- input/kinetics/libraries/combustion_core/version3/reactions.py
- input/kinetics/libraries/combustion_core/version4/dictionary.txt
- input/kinetics/libraries/combustion_core/version4/reactions.py
- input/kinetics/libraries/combustion_core/version5/reactions.py
- input/thermo/libraries/Chernov.py
- input/thermo/libraries/DFT_QCI_thermo.py
- input/thermo/libraries/GRI-Mech3.0-N.py
- input/thermo/libraries/GRI-Mech3.0.py
- input/thermo/libraries/USC-Mech-ii.py
The AdjLists for [C] and [CH] for many kinetic and thermo libraries throughout our database were updated.
According to FFCM-1, H298 of [CH] is 142.40 kcal/mol, while H298 of [CH*] is 209.41 kcal/mol
- In GRI-Mech3.0 (and GRI-Mech3.0-N), Chernov, Naraswamy, USC-Mech-ii H298 of [CH] is 142.77, 142.49, 142.77, 142.77 kcal/mol, respectively.
Therefore, in all the above libraries the AdjList of [CH] was changed to the ground state (having 1 lone pair)
- Dooley is based on GRI-Mech for small radicals, and was changed accordingly.
- Nitrogen_Dean_Bozzelli: [CH] changed to ground state as well, see p. 221 for example
- In Nitrogen_Glarborg_Gimenez_et_al and Nitrogen_Glarborg_Zhang_et_al [CH] was changed to the ground state as well.
The lead was the reaction CH+N2=NCN+H cited from M.C. Lin 2000, …
> Updated AdjLists for [C] and [CH]

- input/kinetics/families/R_Recombination/training/dictionary.txt
- input/kinetics/families/R_Recombination/training/reactions.py
Added
CH3 + CH3 <=> C2H6,
CH3 + C2H5 <=> C3H8, and
C2H5 + C2H5 <=> C4H10
training reactions from Klippenstein 2006 (doi: 10.1039/B515914H)
> Added training reactions to R_Recombination

- input/kinetics/libraries/FFCM1(-)/dictionary.txt
- input/thermo/libraries/FFCM1(-).py
C2H3O is `Oxirane (ethylene oxide) radical' [CH]1CO1, and not C=C[O]
(It appears in FFCM thermo, but does not participate in any of FFCM's reactions)
`H2CC` was also updated
> Corrected the adjList for C2H3O in FFCM1(-) thermo library

- input/kinetics/families/CO_Disproportionation/groups.py
- input/kinetics/families/CO_Disproportionation/rules.py
- input/kinetics/families/CO_Disproportionation/training/dictionary.txt
- input/kinetics/families/CO_Disproportionation/training/reactions.py
- input/kinetics/families/Disproportionation/groups.py
- input/kinetics/families/recommended.py
Added the CO_Disproportionation family.
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/489, where the need for it was first discussed.
This family is similar to the Disproportionation family, but it's specific for the HCO/CO case:
```Y_rad + HCO <=> Y_H + CO```
(another difference is that here the H is abstracted from the radical bearing atom, not from its adjacent neighbor like in the legacy disprop)
The other reason for the distinction of this case from the legacy Disproportionation is the lone pair shift that happens when CO is produced (where C ends up with a partial negative charge and a lone pair, while the O has but one lone pair, see [10.1002/jcc.20477](http://onlinelibrary.wiley.com/doi/10.1002/jcc.20477/abstract;jsessionid=1D00613765AF09CED463953BE5B7301F.f02t01) …
> CO Disproportionation family (db)

- .travis.yml
This the recently merged PR in RMG-Py which has `make test` with tests having no requirements of authentication and `make test-all` with all the tests. So this PR is to update the approriate test mode in RMG-database travis build process.
> make travis to test all the tests

- input/forbiddenStructures.py
- input/thermo/groups/group.py
- input/thermo/groups/polycyclic.py
- input/thermo/groups/radical.py
- input/thermo/groups/ring.py
New thermo groups, mostly ring() and polycyclic() corrections, for species that were found to be important in modeling 1,3-CPD and Natural Gas pyrolysis to form aromatics. New groups mostly based on either M06 or CBS-QB3 calculations. Also added a few globally forbidden species that were problematic due to resonance and unlikely to form anyway.
For the ring() corrections, tree was re-organized slightly, so that even if a strained cyclic species doesn't have an exact match (four consecutive double bonds in a 6-membered ring, for example), it will at least use a cyclic correction that provides a reasonable lower bound on the strain (three consecutive double bonds instead, for example), rather than simply falling up to the most general node.
@KEHANG might be the best reviewer for this PR. …
> Aromatics updates 2 (out of 4): Thermo Groups

- input/kinetics/families/Singlet_Carbene_Intra_Disproportionation/groups.py
This solves #213 by adding the simple forbidden group
```
1 *1 C u0 p1 c-1
```
to `carbene in singlet_carbene_intra_disproportionation`.
@zjburas and I were thinking what would be the best approach (adding `c0` to all node? leaving the forbidden group?) @nyee would you have any suggestions?
> Forbid a charged carbene in singlet_carbene_intra_disproportionation

- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/libraries/Ethylamine/reactions.py
Updated H abstraction rates in the ethylamine library as well as respective training reactions
(rates taken from doi: 10.1016/j.combustflame.2015.10.032)
These rates are calculated in g09 at CBS-QB3 with fancy tunneling.
Compared to experimental values they gave better results for ethylamine pyrolysis and oxidation than our previous in-house CBS-QB3 rates.
> Updated the ethylamine H abstraction reactions by H/CH3/NH2

- input/kinetics/libraries/C2H4+O_Klipp2017/dictionary.txt
- input/kinetics/libraries/C2H4+O_Klipp2017/reactions.py
This PR adds the C2H4+O_Klipp2017 kinetic library.
The reaction of atomic oxygen with ethylene is a fundamental oxidation
step in combustion. Since it involves an intersystem crossing from a
triplet surface to a singlet surface it requires special treatment.
Data taken from http://dx.doi.org/10.1016/j.proci.2016.06.053
> Added the C2H4 +O surface as a kinetic library

- input/kinetics/families/H_Abstraction/NIST/reactions.py
- input/kinetics/families/H_Abstraction/rules.py
- input/kinetics/families/H_Abstraction/training/reactions.py
The evaluateKinetics.py testing script was used to discover training reactions/rules that had very bad comparisons with NIST depository or Leave one out cross validation. 
In this PR, the incorrect rates in the H-abstraction family were fixed. Most of them were from incorrect recording of the A-factor.
> Fixes to units for some training reactions and depositories

- input/forbiddenStructures.py
- Deleted commented-out groups (`N_monorad_3singleBonds`, `N_birad_singlet_2singleBonds`)
- The `[C]` comment was removed, it is no longer true after updating all `[C]` in RMG-database to the correct adjLists.
- Forbidden structures from former ethylamine simulations were removed, they are no longer problematic in the current RMG version (e.g. due to https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1131 and https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1055).
> Removed unnecessary forbidded groups

- input/forbiddenStructures.py
In past RMG models (probably RMG-Java) we used to have two CO species at times, `[C-]#[O+]` and `[C]=O` (the correct and the birad forms of carbon monoxide, respectively). @mjohnson541 confirmed that the birad CO form gets pulled into RMG-Py models' core as well if they are run long enough to include low flux species.
It is noted that we have designated reaction families in RMG to deal with the special reactivity of CO (CO_Disprop and R_Add_COm), hence we don't need to keep the birad form for reactivity reasons. According to @whgreen, this excited birad is 139 kcal/mol higher in energy than ground state CO.
This PR adds both `[C]=O` and the isoelectronic structure `[C]=S` to the forbidden structure list to avoid generating them altogether in future models.
> Forbid CO and CS birads

- input/kinetics/families/lone_electron_pair_bond/groups.py
- input/kinetics/families/lone_electron_pair_bond/rules.py
- input/kinetics/families/recommended.py
The lone_electron_pair_bond family seems very strange.
@nyee and I looked at it at some point and didn't exactly understand its role in RMG (4520b47c3f7b32f230b733f988a4748f1684aa06).
Principally, it should do something like `O(S) + NH3 = [NH3+][O-]`, which is equivalent to `O(S) + NH3 = [NH3]=O` (the products should be resonance structures of each other). I'm emphasizing that the reactant O(S) is in a singlet form, i.e., a closed shell atomic O with 3 lone pairs. Since we shouldn't have atomic `O u0 p3` floating around during RMG jobs in the first place, this family indeed seems harmless.
However, in its current state, other structures do react through it, such as `[R+][O-]`, where O also has 3 lone pairs. An example I just came across is `CH2NH2 + N#[N+][O-] = C([NH2+][O-2][NH2+])C`. …
> Corrections to the strange lone_electron_pair_bond family

- input/kinetics/libraries/JetSurF2.0/dictionary.txt
- input/thermo/libraries/JetSurF2.0.py
- input/thermo/libraries/USC-Mech-ii.py
Old adjlist was for an invalid resonance structure.
I discovered this randomly while testing RMG-website because it was actually causing unexpected issues. For example, [searching for benzene + H gives the odd resonance structure as the third result](http://rmg.mit.edu/database/kinetics/results/reactant1=1%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B6,S%7D%20%7B7,S%7D%0D%0A2%20%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B8,S%7D%0D%0A3%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,D%7D%20%7B9,S%7D%0D%0A4%20%20C%20u0%20p0%20c0%20%7B3,D%7D%20%7B5,S%7D%20%7B10,S%7D%0D%0A5%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B6,D%7D%20%7B11,S%7D%0D%0A6%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,D%7D%20%7B12,S%7D%0D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0D%0A8%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0D%0A9%20%20H%20u0%20p0% …
> Fix adjlist for C6H5 in JetSurf2.0

- input/kinetics/libraries/BurkeH2O2inArHe/reactions.py
- input/kinetics/libraries/BurkeH2O2inN2/reactions.py
This PR adds six H2/O2 reactions to the Burke kinetic libraries.
Three of these reactions were so far missing from RMG (i.e., not found in libraries nor belong to any family):
- `OH + OH <=> H2 + O2`
- `H2O + O <=> H2 + O2`
- `H2O2 + O <=> H2O + O2`
Two additional reactions were added as training reactions in addition to the Burke libraries:
- `HO2 + H <=> H2O + O` (Substitution_O)
- `HO2 + H <=> H2O2` (R_Recombination)
It is noted that 'HO2 + H <=> H2O + O` is considered to have a negligible rate.
An additional reaction fits the Birad_R_Recombination family, yet since the kinetics is only available in a ThirdBody PDep form, it wasn't added as a training reaction, and only added to the libraries:
- `OH + O <=> HO2`
ref: Table III in [Burke et al.](http://dx.doi.org/10.1002/kin.20603) …
> Added additional H2/O2 reactions to the Burke kinetic libraries

- input/kinetics/libraries/SOx/dictionary.txt
- input/kinetics/libraries/SOx/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgH2S/reactions.py
- input/kinetics/libraries/Sulfur/H2S+S=2SH_1bar/dictionary.txt
- input/kinetics/libraries/Sulfur/H2S+S=2SH_1bar/reactions.py
- input/thermo/libraries/SOxNOx.py
- input/thermo/libraries/SulfurLibrary.py
- **Fixed SH + SH <=> HSSH in GlarborgH2S kinetic library**
The original study (DOI 10.1002/kin.21055) reported a model in which the
high-P rate of the reaction in the title was deliberately reduced to fit
the experiment (See Fig. 4). This PR assigns the original pre-exponential
factor value back.
- **Added kinetics from Marshall1995 to the SOx library**
- **Added thermo of HSO and HOS from Marhsall1995 to the SOxNOx library**
- **Removed the `SO2(T) <=> SO2` transition from the SOx library**
It should be treated better using the Singlet_Val6_to_triplet library
- **Updated `SO + O <=> SO2` in the SOx library**
- **Updated `HOSO <=> SO + OH` in the SOx library**
- **Added the `Sulfur/H2S+S=2SH_1bar` library**
- **Updated H298 and uncertainties in thermo SOxNOx library**
- **Added the SH + …
> Fixed various sulfur library entries

- input/forbiddenStructures.py
- input/thermo/groups/ring.py
- input/thermo/libraries/primaryThermoLibrary.py
The `Ods` globally forbidden group forbids oxygen with both double and single bonds.
Now that atomTypes were updated (`O4dc` describes `-[O+]=`), we can correctly (and should) represent such structures, e.g., ozone `[O-][O+]=O` (we also have both thermo and kinetics for ozone from several new libraries).
Since currently GAV is doing a terrible job for ozone's thermo (`group(O2s-CsCs) + group(O2s-CsCs)`, missing the `-[O+]=` of course, but also the double bond on the terminal O isn't captured), and ozone now might pop in different jobs, a respective entry was also added to the PrimaryThermoLibrary.
We should check that nothing else significantly changes following this PR (-tests).
In this PR the `Ods` group was modified so that O cannot have both double and single bonds **while** keeping a …
> Allow ozone by modifying the Ods globally forbidden group

- input/kinetics/libraries/Lai_Hexylbenzene/dictionary.txt
- input/kinetics/libraries/Lai_Hexylbenzene/reactions.py
- input/thermo/libraries/Lai_Hexylbenzene.py
**Added one training reaction in R_addition_MultipleBond**
Training reaction rate constant added for the following reaction:
1-butyl radical + Styrene --> CCCCC[CH]C1C=CC=CC=1
Rate constant calculated by Lawrence Lai, 2017, CBS-QB3 Level of theory
**Added thermo library named Lai_Hexylbenzene**
Added Library file that contains CBS-QB3 thermo calculations performed by Lawrence Lai in 2017.
Species include:
Hexylbenzene
Styrene
Hexylbenzene Radicals on all aliphatic positions
n-alkylbenzenes from Toluene to Pentylbenzene
Alkylbenzyl radicals (radical positioned adjacent to aromatic ring) from
benzyl radical to pentylbenzyl radical
Indane
Ethyltetralin
C1=CC=C2CCCC2[CH]1
CCC1CCCC2=CC=C[CH]C21
1-Butyl radical
1-Pentyl radical
CC1=C[CH]C=CC1
CC1[CH]C=CCC=1
C[C]1C=CCC=C1
CC1C=C[CH]C=C1 …
> Hexylbenzene library lai

- input/kinetics/families/H_Abstraction/groups.py
This sets the nodalDistance of the O2b group in H_abstraction to 15.
> prevent the use of O2b rules in H_abstraction for abstractions not done by O2b

- input/thermo/groups/polycyclic.py
- input/thermo/groups/radical.py
Groups added/editted are:
radical(Benzyl_S)
radical(Benzyl_P)
radical(C=CCJC=C-cyclohexadiene)
radical(CJC=CC=C-cyclohexadiene)
radical(C=CCJ(C)C=C-cyclohexadiene)
polycyclic(s2_5_6_ben)
polycyclic(s2_6_6_ben)
polycyclic(s2_5_6_diene_0_3)
polycyclic(s2_6_6_diene_0_3)
Calculations done by Lawrence Lai, 2017, can be found in
pharos/laitcl/Gaussian
> Added and edited thermo groups entries based on CBS-QB3 Calculations

- input/kinetics/libraries/Nitrogen_Dean_and_Bozzelli/reactions.py
Should be `s^-1`, not `1/s`.
The latter results in a `KeyError: '1/s'` when these reactions are searched for on the RMG website.
> Corrected s^-1 units in N_D&B kinetic family

- input/kinetics/families/H_Abstraction/rules.py
A longDesc contradicting the shortDesc was improperly added to two rules during the commit "Manual merge of RMG-Java 8ce558. H_Abstraction family updated" this pull request removes the improper longDesc from these rules.
> Fixes the longDesc attribute of two nodes that were improperly changed

- input/kinetics/families/CO_Disproportionation/training/dictionary.txt
- input/kinetics/families/CO_Disproportionation/training/reactions.py
- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
Mainly from the Klippenstein_Glarborg2016 library:
```
High-pressure oxydation of methane
Hamid Hashemi, Jakob M. Christensen, Sander Gersen, Howard Levinsky, Stephen J. Klippenstein, Peter Glarborg
Combustion and Flame 172, 2016, 349-364
http://dx.doi.org/10.1016/j.combustflame.2016.07.016
```
And one reaction from GRI-Mech3.0 (since it was in a MultiArrhenius form in the above paper - the rates are comparable)
The Klippenstein_Glarborg2016 library is a recently updated C/O/H kinetics library. I did not go through each of the reactions to track its fundamental source and determine level of theory or whether it is an experimental value, hence I gave all reactions a rank of 3.
> Added H_Abstraction and CO_Disprop training reactions

- input/kinetics/families/Diels_alder_addition/groups.py
They could be matched in the product template but were not included in the reactant template, causing undeterminable kinetics errors.
> Add CO and CS to ene group in Diels_alder_addition

- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/libraries/Sulfur/GlarborgNS/reactions.py
- input/kinetics/libraries/primaryNitrogenLibrary/LowT/reactions.py
This PR fixes just one error of the many potential TST and collision rate violators reported in #275.
Also, a low-T rate of `CN + NCO <=> NCN + CO` was added to the primaryNitrogenLibrary.
We could either merge, or continue adding related fixes to this PR.
> Miscellaneous minor database fixes

- .travis.yml
For some reason, the generatePairs unit test fails if the database test is run first. This doesn't seem to make any sense, but switching the order fixes it, so we're going to do that for now.
The behavior is also not reproducible locally
> Change order of unit tests for travis build

- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
- input/kinetics/families/Intra_ene_reaction/training/dictionary.txt
- input/kinetics/families/Intra_ene_reaction/training/reactions.py
- input/kinetics/families/R_Addition_COm/training/dictionary.txt
- input/kinetics/families/R_Addition_COm/training/reactions.py
- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- input/kinetics/families/R_Recombination/training/dictionary.txt
- input/kinetics/families/R_Recombination/training/reactions.py
- input/kinetics/families/intra_H_migration/training/dictionary.txt
- input/kinetics/families/intra_H_migration/training/reactions.py
This is based on #271 which should be merged first.
Add training reaction on C3H3OO surface
1. C3H3O2(II) <=> C3H2OOH calculated by Jim on 05/30/2017, CBS-QB3 with hindered rotor consideration
2. C3H3+O2 <=> C3H3O2(I) Fitted TST rate from Hahn et al. Faraday Discuss., 2001, 119, 79-100 Figure 4
3. C3H3+O2 <=> C3H3O2(II) Fitted TST rate from Hahn et al. Faraday Discuss., 2001, 119, 79-100 Figure 4
Add training reactions of C3H3 + C3H3 and H recombination
1. C3H3+C3H3 <=> three C6H6 products, Phys. Chem. Chem. Phys., 2007, 9, 4259–4268, Georgievskii et al.
2. C3H3 + H <=> propyne and allene, J. Phys. Chem. A 2007, 111, 3789-3801, Harding et al.
Add training reactions of C3H3+H2 H-abstraction
C3H3+H2 <=> propyne or allene+H, both directions
Molecular information from J. Phys. Chem. A 2011, …
> Added training reactions found to be important in rich-methane modeling

- input/forbiddenStructures.py
Changes:
- Removed C8H7S2J and C8H7S2J(2): imported 6 years ago from RMG-Java, no apparent reason why we can't handle this with current RMG
- Combined {O3 O3. O3.. O4} into single group: there's no reason for having 4 groups when 1 would be sufficient
- Adjusted cyclobutyne bond orders: we're not going to see a triple bonded atom with another double or triple bond, added benzene bond to the bond opposite to the triple bond
- Removed s2_3_4_yne_1, s2_4_4_yne_1, s2_4_5_yne_5, and s2_4_6_yne_6: unnecessary since these are already forbidden by cyclobutyne
- Removed strained_tetracyclic_1, strained_tricyclic_1, strained_tricyclic_2, and strained_tricyclic_3: most time consuming forbidden structures, crashes due to reaction generation should be addressed by fixing RMG-Py, crashes due to Clar …
> Clean up global forbidden structures

- input/transport/libraries/NOx2018.py
Where `shapeIndex` 0, 1, 2 is a single atom / linear molecule / nonlinear molecule, respectively.
> Corrected shapeIndices in NOx2018 transport library

- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
Four new training reactions indexed 186 through 189 are added to
R_Addition_MultipleBond. These reactions include
Toluene + CH3 --> CC1[CH]C(C)C=CC=1
Toluene + CH3 --> CC1=CC=C[CH]C1C
Toluene + CH3 --> CC1C=CC(C)[CH]C=1
Toluene + CH3 --> CC(C)1C=CC=C[CH]1
In addition, five previously incorrect reaction rates are corrected
These reactions are indexed 78 through 82
The five reactions had their A factors divided by a factor of two
to account for the previously incorrect spin multiciplicity used
> Added Four New Reactions to R_Addition_MultipleBond, Fixed old rates

- input/kinetics/families/CO_Disproportionation/groups.py
- input/kinetics/families/Disproportionation/groups.py
- input/kinetics/families/H_Abstraction/groups.py
since N5t isn't physical. Note that a charged nitrogen atom with valance 5 and a triple bond (N5tc), which is the physical form, is still allowed.
Should be merged before https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1418.
> Removed N5t atomType from the database

- input/forbiddenStructures.py
- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/families/intra_NO2_ONO_conversion/rules.py
- input/kinetics/families/intra_NO2_ONO_conversion/training/dictionary.txt
- input/kinetics/families/intra_NO2_ONO_conversion/training/reactions.py
- input/kinetics/families/ketoenol/groups.py
- input/kinetics/libraries/CurranPentane/dictionary.txt
- input/kinetics/libraries/Klippenstein_Glarborg2016/dictionary.txt
- input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
- input/kinetics/libraries/NOx2018/dictionary.txt
- input/kinetics/libraries/Nitrogen_Dean_and_Bozzelli/dictionary.txt
- input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/dictionary.txt
- input/kinetics/libraries/Nitrogen_Glarborg_Zhang_et_al/dictionary.txt
- input/kinetics/libraries/Sulfur/GlarborgH2S/alt/dictionary.txt
- input/kinetics/libraries/Sulfur/GlarborgH2S/alt/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgH2S/reactions.py
- input/kinetics/libraries/primaryNitrogenLibrary/LowT/dictionary.txt
- input/kinetics/libraries/primaryNitrogenLibrary/dictionary.txt
- input/thermo/libraries/CurranPentane.py
- input/thermo/libraries/DFT_QCI_thermo.py
- input/thermo/libraries/Klippenstein_Glarborg2016.py
- input/thermo/libraries/NOx2018.py
- input/thermo/libraries/NitrogenCurran.py
- input/thermo/libraries/primaryNS.py
- input/thermo/libraries/thermo_DFT_CCSDTF12_BAC.py
This PR adds:
- A rate for `H2S + O2 <=> SH + HO2` to primarySulfurLibrary
- Thermo value correction for `OSO(T)` in the primaryNS library (`OOS(T)` was also updated)
- A sublibrary for GlarborgH2S
- AdjList updates in thermo libraries
> Miscellaneous heteroatoms fixes and additions

- input/thermo/libraries/SABIC_aromatics.py
This library includes species of C6H5+O2 PES, first_to_second_ring 10 pathways (2017 Mebel), naphthyl+acetylene HACA surfaces, biphenyl decomposition, and other large PAHs up to 	Benzo[a]pyrene (C20H12)"
Dr. Istvan Lengyel calculates species (except for biphenyl C12H10 calculated by Max Liu) at CBS-QB3 in Gaussian09. The calculation was done for the lowest energy conformer, but the rotor scan was not performed. By using CanTherm, the thermo properties were evaluated, where bond corrections value in Petersson et al. 1998 (https://doi.org/10.1063/1.477794 bond corrections) were used since it considered aromatic species.
> Add SABIC_aromatics library

- input/kinetics/families/Disproportionation/groups.py
- input/kinetics/families/Disproportionation/training/dictionary.txt
- input/kinetics/families/Disproportionation/training/reactions.py
This commit was previously in #293. However, we decided that more work still needs to be done for that PR, so I am putting this in its own PR so that it can be merged first.
This commit adds benzene bond groups for the XH tree in disproportionation, thereby allowing formation of arynes in this family starting with aromatic structures. This is especially important given the imminent removal of Kekule structures as being reactive.
For testing, checking RMG-tests should be sufficient. This should only affect the aromatics test, if at all. Changes should be negligible since the Kekule structure could react before.
> Add benzene bond groups to Disproportionation

- .gitignore
Quick PR to add PyCharm to gitignore, since GitKraken no longer reads a User's personal global .gitignore
> Add PyCharm Files to .gitignore

- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- input/kinetics/families/R_Recombination/training/reactions.py
As described in title. Erroneous reactions were identified by new unit test in ReactionMechanismGenerator/RMG-Py#1538.
> Correct A factor units in training depositories

- input/kinetics/libraries/GRI-Mech3.0-N/dictionary.txt
- input/thermo/libraries/GRI-Mech3.0-N.py
- input/thermo/libraries/GRI-Mech3.0.py
NH in GRI should be the `NH(T)` form, not the `NH(S)` form.
The H298 of `NH(S)` is about 120 kcal/mol, but the NH structure in the GRI libraries, which currently has the adjList of `NH(S)`, has H298 of 85 kcal/mol, which is the correct value for `NH(T)`.
Values for comparison are available in the primaryNS library (the singlet form) and in the NitrogenCurran library (the triplet form)
> Corrected NH structure in GRI libraries

- input/thermo/libraries/CBS_QB3_1dHR.py
- input/thermo/libraries/thermo_DFT_CCSDTF12_BAC.py
Calculated automatically using ARC 1.0.0
AIBN ([azobisisobutyronitrile](https://en.wikipedia.org/wiki/Azobisisobutyronitrile)) is a radical initiator. Here we give thermodata for it as well as for its immediate decomposition products.
AIBN calcs done at CBS-QB3
Calcs for the smaller species were done at CCSD(T)-F12/DFT
The data was added to the appropriate libraries in RMG
**This is the first PR adding thermo calculated automatically**. My only manual involvement was considering a rotor ARC mistakenly invalidated. I tried to provide a detailed description, and avoided reporting on execution time.
> Added AIBN and its decomposition products to thermo libraries

- input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
- input/kinetics/families/Intra_R_Add_Exocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Exocyclic/training/reactions.py
Should be pretty straightforward. The Intra_R_Add_Endocyclic reactions were added by me a long time ago. Someone else was supposed to add the Intra_R_Add_Exocyclic reactions, but it never happened. Prior data for these reactions were from rate rules only.
The intra_H_migration reactions from the same paper also do not seem to have been added, but that'll be another PR when I get around to it.
Reference: [Wang, K.; Villano, S. M.; Dean, A. M. J. Phys. Chem. A 2015, 119 (28), 7205–7221.](http://pubs.acs.org/doi/abs/10.1021/jp511017z)
> Add Intra_R_Add_Exocyclic training reactions from Wang et al. 2015

- input/thermo/libraries/GRI-Mech3.0.py
While N2O triplet exists, according to the data here, this entry was meant to be the singlet.
The triplet N2O (GRI-Mech vs. NNOJJ):
Singlet N2O:
Tag @dranasinghe for discovering this
> Corrected the adjlist (and multiplicity) of N2O in GRI_Mech

- input/solvation/libraries/solute.py
I found some minor typos in solutes' names in `input/solvation/libraries/solute.py` and fixed them.
I also found two solutes with wrong SMILES, meaning that their SMILES do not match the names of the solutes. To double-check that it is the SMILES that are wrong not the labels, I compared the values of the solute parameters in `input/solvation/libraries/solute.py` to those I found in literature. This confirmed that the labels of these two solutes are right and SMILES were wrong, so I fixed the SMILES to those that match with their labels.
> Fixed typo and wrong SMILES in solute library

- input/FilterArrheniusFits.yml
- scripts/generateFilterArrheniusFits.ipynb
By filtering reactions we add a pre-filtering step before the step of reacting species together (slow), which prevents species from reacting together when the reactions are expected to be negligible throughout the simulation. Currently, unimolecularThreshold, bimolecularThreshold, and trimolecularThreshold are binary arrays storing flags for whether a species or a pair of species are above a reaction threshold. For a unimolecular rate, this threshold is set to True if the unimolecular rate of reaction 𝑘 reaction  k for a species A 
at any given time 𝑡 t in the reaction system, where
For a bimolecular reaction occuring between species A and B, this threshold is set to True if the bimolecular rate
where 𝑘𝑡ℎ𝑟𝑒𝑠ℎ𝑜𝑙𝑑=filterThreshold is set by the user in the input file and its default value is …
> Simultaneous Update of RMG-Py and RMG-database for customized reaction filter criteria for each reaction family.

- input/kinetics/families/1,2_NH3_elimination/groups.py
- input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/dictionary.txt
- input/kinetics/libraries/Nitrogen_Glarborg_Zhang_et_al/dictionary.txt
- input/kinetics/libraries/primaryNitrogenLibrary/dictionary.txt
`*3 N` cannot have 0 lone pairs, since it looses a lone pair in the recipe.
This fix prohibits species such as
```python
<Molecule "[NH-][NH2+]NN">
1  *3 N u0 p0 c+1 {2,S} {4,S} {5,S} {6,S}
2  *2 N u0 p1 c0 {1,S} {3,S} {7,S}
3  *1 N u0 p1 c0 {2,S} {8,S} {9,S}
4     N u0 p2 c-1 {1,S} {10,S}
5     H u0 p0 c0 {1,S}
6     H u0 p0 c0 {1,S}
7  *4 H u0 p0 c0 {2,S}
8     H u0 p0 c0 {3,S}
9     H u0 p0 c0 {3,S}
10    H u0 p0 c0 {4,S}
```
from reacting in `1,2_NH3_elimination`.
Edit: Also added a minor unrelated commit to update the structure of HON
> Modified the 1,2_NH3_elimination root group

- .travis.yml
Environment file name has changed, and we need the py3 version of q2dtor.
> Update .travis.yml following RMG-Py changes

- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/libraries/DMSOxy/dictionary.txt
- input/kinetics/libraries/DMSOxy/reactions.py
- input/thermo/groups/group.py
- input/thermo/groups/longDistanceInteraction_noncyclic.py
- input/thermo/groups/radical.py
- input/thermo/libraries/SulfurLibrary.py
This pull request encompasses several changes to the database related to my work on DMS oxidation. 
1. The largest change is a revamp of the group additivity scheme for oxygenated sulfur molecules. 
2. It also includes an additional reaction library,
3. Several more training reactions for H Abstraction,
4. A bugfix for the Intra_R_Add_Endocyclic Family nodes (The top node wasn't sufficiently general)
> Dms oxy changes

- input/thermo/groups/polycyclic.py
- input/thermo/groups/radical.py
- input/thermo/groups/ring.py
New corrections for a couple of strained polycyclic species, selected based on the fact that RMG was adding them to models despite the fact that they seem very unstable.
First commit contains 1 bicyclic and 3 tricyclic corrections. Because these are "aromatic" with multiple possible bond arrangements, multiple groups had to be made for each species. The bicyclic compound was calculated using CBS-QB3, while the tricyclic ones were calculated using M06-2X/cc-pVTZ due to size (same level as large portion of the polycyclic corrections).
The second commit contains 5 bicyclo C6 compounds (s2_4_4 in polycyclic.py notation) with various degrees of unsaturation. The goal was to fill in all missing double bonded bicyclics of this type, but these 5 were the only ones which converged to the desired …
> Add polycyclic corrections for some strained cyclic species

- input/kinetics/families/R_Recombination/groups.py
- input/kinetics/families/R_Recombination/rules.py
Improved generated tree using SABIC_aromatics and generating resonance structures before calculating thermo. Should mostly fix #353.
> Improve R_Recombination Generated Tree

- input/kinetics/libraries/NOx2018/reactions.py
I assume some isomorphism checker neglected the multiplicity
when importing this model
and thought CH2 and CH2(S) were isomorphic, and
CH2CHN(S) and CH2CHN, so it merged the kinetics and/or
marked things as duplicates when they shouldn't be.
This commit fixes that (by hand) but unfortunately the numbering
is now off and there are multiple reactions with the same index
attribute.
> Remove incorrect Duplicate merges and flags in NOx2018

- input/thermo/groups/group.py
This fix solves issue #374 and points node Cds-CdSH to an existing group called Cds-CdsSH.
> Fix Node error for Cds-CdSH

- input/solvation/libraries/solvent.py
**This pull request requires the simultaneous update of RMG-Py and RMG-database, so the Travis builds will fail until the relevant RMG-Py pull request is merged **
For each solvent, 'name_in_coolprop' is added as a new feature of solventData. CoolProp is an external packaged used for fluid properties calculations. It takes a solvent's name as an input which is saved as 'name_in_coolprop'. This name is different from the current RMG solvent's name and therefore this new feature has to be added.
If solvents are not availalbe in CoolProp, its 'name_in_coolprop' is set to None.
CoolProp will be used in RMG-Py to do temperature-dependent solvation thermochemistry calculation.
> Added a new attribute for solvent data relevant to T-dependent solvation thermochemistry

- input/kinetics/families/intra_H_migration/groups.py
Forbid intra_H migration in a 7-membered ring by a rad adjacent to the ring at the far end sites (symmetric, so only one forbidden group was added)
> Forbid intra_H migration in a 7-membered ring

- scripts/importChemkinLibrary.py
The script `importChemkinLibrary.py` created kinetic libraries with inconsistent labeling and indexing; this caused mechanisms to fail immediately when trying to restart them and run them further in RMG using the newly created libraries. Additional details can be found in issue #399 and in #72 as well.
Previously, using `str(reaction)`, called the `__str__` method for `RMG-Py/rmgpy/reaction.py` which used the index when creating the kinetics library: `reactions.py`. However, this format was inconsistent with the corresponding `dictionary.txt` that did NOT use indices. 
The fix is to instead call the `to_labeled_str` method, whose default sets the `use_index` flag to `False`, thus making the format consistent. Indeed, this fix allows the merged mechanism to restart without errors.
> Fix indexing import chemkin library

- input/quantum_corrections/data.py
Previously this data was stored in RMG-Py, but data like this should be stored in RMG-database.
This is the twin of RMG-Py PR [1870](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1870)
> Add data for AEC, BAC, and frequency scale factors

- input/kinetics/families/2+2_cycloaddition_Cd/rules.py
I realized that removing the rate rule in rules.py in my merged PR #395  can cause trouble estimating rates for some reactions that I didn't encounter in the testing I did for that PR. Therefore, I've taken the rate from its only training reaction and put it into rules.py. I've tested this locally with those troubled reactions, and it worked fine.
> Added a rate rule in 2+2_cycloaddition_Cd/rules.py

- input/quantum_corrections/data.py
- input/reference_sets/main/Ammonia.yml
- input/reference_sets/main/Chloromethane.yml
- input/reference_sets/main/Dibromine.yml
- input/reference_sets/main/Dichlorine.yml
- input/reference_sets/main/Difluorine.yml
- input/reference_sets/main/Dihydrogen.yml
- input/reference_sets/main/Dinitrogen.yml
- input/reference_sets/main/Dioxygen.yml
- input/reference_sets/main/Disulfur.yml
- input/reference_sets/main/Hydrogen bromide.yml
- input/reference_sets/main/Hydrogen chloride.yml
- input/reference_sets/main/Hydrogen fluoride.yml
- input/reference_sets/main/Hydrogen sulfide.yml
- input/reference_sets/main/Methane.yml
- input/reference_sets/main/Methyl.yml
- input/reference_sets/main/Water.yml
Adds new CCCBDB reference data to the species that will be used for atom energy fitting (experimental geometries, atomization enegies, and zero-point energies). Corresponds to ReactionMechanismGenerator/RMG-Py#1950.
Also adds the updated atom energies for wB97M-V/def2-TZVPD.
> Atom energy fitting

- input/thermo/libraries/SABIC_aromatics.py
Original values were very off in enthalpies for these two species and caused troubles for the activation energies of two reversed training reactions in Intra_R_Add_Endocyclic. New values were calculated at CBS-QB3 level of theory with BAC using Gaussian09. C10H11 library also has an entry of C10H11_5, which was calculated at CSB-QB3  level of theory, plotted for comparison.
> Updated C9H11_16 and C10H11_5 entries in SABIC_aromatics

- input/thermo/groups/polycyclic.py
This is a very minor PR. I realized that it's better to use a boarder atom type for the group in polycyclics. I changed the atom type from teh very specific Cs to a boarder R!H in my previously added group s3_5_7.
> Minor: Change atom type from Cs to R!H for s3_5_7 polycyclics

- input/thermo/libraries/JetSurF2.0.py
- input/thermo/libraries/Klippenstein_Glarborg2016.py
- input/thermo/libraries/Narayanaswamy.py
This PR aims to correct the thermo entries of [C]=C. some of them are incorrectly marked as values for triplet [C]=C.
**How to distinguish?**
According to my calculation and values in QCI_DFT, [C]=C values in JetSurF2.0, Klippenstein_Glarborg2016, and Narayanaswamy are very close to the value of singlet [C]=C in QCI_DFT, instead of triplet [C]=C.
E.g.,
dG(triplet, 1000K) ~ 84 kcal/mol
dG(singlet, 1000K) ~  39 kcal/mol
> Correct Thermo of [C]=C

- input/kinetics/libraries/JetSurF2.0/dictionary.txt
- input/kinetics/libraries/Klippenstein_Glarborg2016/dictionary.txt
- input/kinetics/libraries/Narayanaswamy/dictionary.txt
This is a follow-up PR of H2CC correction (see #435).
Thanks to @mliu49's issue #365, I realize that not only thermo libraries but also kinetic libraries are suffering from this issue. Since kinetic library and thermo library with the same library name (JetSurF2.0, Klippenstein_Glarborg2016, and Narayanaswamy) should come from the same mechanism file, H2CC (with the same label) should be the same species in both libraries. So, I corrected H2CC in the mentioned three libraries. I also checked other kinetic libraries if they have a thermo Lib. counterpart, and their H2CC multiplicities are correctly assigned. 
I didn't further check any other kinetic libraries, since it is hard to tell whether their H2CC should be singlet or triplet. However, I would say singlet H2CC has a higher chance to …
> Correct Kinetic libraries with [C]=C

- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
Previously, RMG rate rules did a very poor job of estimating the rate of -CH2- + OH reactions (the bottom purple line).
To improve performance, 3 training reactions are added (-CH2- of n-butane and n-pentane + OH). The sources of the rates coefficients are noted in the description section. Although rate coefficients from a high level of theory calculations are desired, I can only find rates from fittings combining low-T experiment and shock tube results. Since other models like NUIG pentane or LLNL heptane are also using the same set of rate (actually rate rules based on these values), I think these values are acceptable.
The updated estimation is shown as the pink line. As can be seen, it is much closer to the rates of C3 / C4. As a comparison, rates of -CH3 + OH are also listed in the …
> Add training reaction for -CH2- + OH

- input/thermo/libraries/surfaceThermoPt111.py
CN_ads is monodentate and not bidentate like the adjacency list and LSR comment indicated.
The thermo itself is not affected by the number of sites since the harmonic oscillator model was used.
> Corrected adjacency list and longDesc in CN_ads thermo entry

- input/kinetics/families/Surface_Adsorption_Abstraction_vdW/groups.py
This family was causing charged N species, as seen in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2038 and this should fix that.
> FIXUP: fixing up typos in Surface_Adsorption_Abstraction_vdW family

- input/kinetics/families/Surface_Abstraction_vdW/training/dictionary.txt
- input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
- input/kinetics/families/Surface_Addition_Single_vdW/training/dictionary.txt
- input/kinetics/families/Surface_Addition_Single_vdW/training/reactions.py
- input/kinetics/families/Surface_Adsorption_vdW/training/dictionary.txt
- input/kinetics/families/Surface_Adsorption_vdW/training/reactions.py
- input/kinetics/families/Surface_Dissociation_Double_vdW/training/dictionary.txt
- input/kinetics/families/Surface_Dissociation_Double_vdW/training/reactions.py
- input/kinetics/families/Surface_Dissociation_vdW/training/dictionary.txt
- input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
- input/kinetics/libraries/Surface/Deutschmann_Ni/dictionary.txt
- input/kinetics/libraries/Surface/Deutschmann_Ni/reactions.py
Now that the new vdw families have been merged in, this PR distributes the rates from the deutschmann library to their corresponding vdw family as training reactions.
this is related to https://github.com/ReactionMechanismGenerator/RMG-database/issues/430 and https://github.com/comocheng/wiki/issues/614
> Distributing catalytic deutschmann rates into vdw families

- input/kinetics/families/1,2_Insertion_CO/groups.py
This is a simple patch to allow `CO + H----C(R)=O  <=> H--C(=O)--C(R)=O` reactions to be generated by `1,2_Insertion_CO`.
I found this type of reaction (actually, TSs) in the training data from Colin et al. (https://pubs.acs.org/doi/full/10.1021/acs.jpclett.0c00500). Due to limited training reactions, only the very top node is modified and no child node is added. If the reviewer thinks it is important, I can make further modifications.
> Allow CO insertion to H--C(R)=O

- input/thermo/groups/adsorptionPt111.py
When we don't skip nitrogen entries in the database tests, we get the following error in the `adsorptionPt111` thermo tree
```
Thermo groups adsorptionPt111: Entry is accessible? ... ERROR:root:
In group adsorptionPt111, a sample molecule made from node (NR2CR3)* returns node (CR3NR2)* when descending the tree.
Sample molecule AdjList:
1 N u0 p1 c0 {2,S} {6,S} {7,S}
2 C u0 p0 c0 {1,S} {3,S} {4,S} {5,S}
3 H u0 p0 c0 {2,S}
4 H u0 p0 c0 {2,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {1,S}
7 H u0 p0 c0 {1,S}
8 X u0 p0 c0
Origin Group AdjList:
1 N  u0 p1 c0 {2,S} {3,S} {4,S}
2 Cs u0 p0 c0 {1,S}
3 R  u0 p0 c0 {1,S}
4 R  u0 p0 c0 {1,S}
5 X  u0 p0 c0
Matched group AdjList:
1 C u0 p0 c0 {2,S} {3,S} {4,S} {5,S}
2 N u0 p1 c0 {1,S} {6,S} {7,S}
3 R u0 p0 c0 {1,S}
4 R u0 p0 c0 {1,S}
5 R u0 p0 c0 {1,S}
6 R u0 p0 …
```
> adsorptionPt111 nitrogen nodes fix

- input/solvation/groups/group.py
- input/solvation/groups/halogen.py
- input/solvation/groups/longDistanceInteraction_cyclic.py
- input/solvation/groups/longDistanceInteraction_noncyclic.py
- input/solvation/groups/polycyclic.py
- input/solvation/groups/radical.py
- input/solvation/groups/ring.py
- input/solvation/libraries/solute.py
- input/solvation/libraries/solvent.py
_**Note that this pull request requires simultaneous updates of RMG-Py and RMG-database. The pull request on RMG-Py solvation_thermo_GAV branch is https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2112. The last commit needs to be removed before merging this branch.**_
The previous group additivity (GAV) method for solvation thermo uses very limited number of groups. This pull request will upgrade the solvation thermo GAV method that uses a lot more groups. Also, this pull request adds a lot more solvents and solutes to the solvent and solute libraries. 
The major changes include:
1. The solvation GAV now follows an approach similar to the gas-phase thermo GAV and uses `group`, `ring`, `polycyclic`, `longDistanceInteraction_cyclic`, `longDistanceInteraction_noncyclic`, `halogen`, …
> Upgrade solvation thermo GAV and solute & solvent libraries

- input/kinetics/families/1,3_Insertion_RSR/training/reactions.py
- input/kinetics/families/1,3_NH3_elimination/training/reactions.py
- input/kinetics/families/Surface_EleyRideal_Addition_Multiple_Bond/training/reactions.py
Noticed that a few families have a training reaction file with a "name" header that doesn't match the family name.
Not sure why this metadata is hard-coded and not checked, but for now I just fixed the errors.
> Fix typo in training reactions name field.

- input/thermo/groups/adsorptionPt111.py
- input/thermo/libraries/surfaceThermoPt111.py
The errors were due to an incorrect gas-phase reference, that assumed a liquid phase H2O in the ATcT reference of the fictitious reaction. This is corrected here, assuming gas-phase H2O which is consistent with the other reference species as well as the surface heats of formation at 0K.
Small additional fixes:
1. Fixed O, N and H adsorption corrections to that used an incorrect gas-phase reference for a different reason (missing term in fictitious reaction)
2. Fixed HNO thermo by using the harmonic oscillator approximation instead of the 2D gas model, since the binding energy of HNO is stronger than 100 kJ/mol.
Update:
Change of plans, it seems that it will be more accurate and consistent to use ATcT heats of formation for the gas-phase counterparts in calculation of the adsorption …
> Fixed enthalpy errors in adsorption corrections for O-containing species on Pt(111)

- input/kinetics/families/Surface_Abstraction_Single_vdW/groups.py
- input/kinetics/families/Surface_Abstraction_vdW/groups.py
- input/kinetics/families/Surface_Addition_Single_vdW/groups.py
- input/kinetics/families/Surface_Adsorption_Abstraction_vdW/groups.py
- input/kinetics/families/Surface_Dissociation_Double_vdW/groups.py
- input/kinetics/families/Surface_Dissociation_vdW/groups.py
- input/kinetics/families/Surface_Dual_Adsorption_vdW/groups.py
Relating to our previous discussions, the Van der Waals species have ```multiplicity [1]```, which means the unpaired radical is 0. This PR revised the entries in the surface vdW families which defined the unpaired radicals of vdW species as ```ux``` rather than ```u0```. I also made a little change of ```Xv  ux px cx``` to ```Xv  u0 p0 c0``` in some surface vdW families.
> Fix the number of unpaired radicals in surface vdW families.

- input/kinetics/families/2+2_cycloaddition/groups.py
As mentioned in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1761, the 2pi + 2pi cycloaddition was thermally forbidden. The definition of current root node prevents the generation of such reaction from the forward direction, but nothing stops RMG to try creating this reaction from the reverse direction (luckily this doesn't appear commonly, as I just encounter the first ever of such case). 
Currently, if one runs the following code, one would get `UndeterminableKineticsError`. This is because RMG labels the four ring structure in the product and tries to use the forward reaction to find the kinetics, but the root node is defined in the way to prevent a 2pi + 2pi cycloaddition.
```
from rmgpy import settings
from rmgpy.data.rmg import RMGDatabase
from rmgpy.molecule.molecule …
```
> Add forbidden group to ban thermally forbidden 2pi + 2pi cycloaddition

- input/solvation/libraries/solvent.py
Some minor errors are fixed and new minor things are added in the solvent library:
1. Some of the solvent species did not have `None` for `dHsolvCount` although they need to be set to `None`. These are fixed.
2. Some of the wrong references are fixed.
3. `name_in_coolprop` is newly added for 9 solvents. (`name_in_coolprop` is the name of the solvent that is used in a conda package CoolProp. Temperature-dependence solvation property calculations are available for the solvents with `name_in_coolprop`)
4. The name of the solvent entry 11 is fixed to `1,1-dichloroethane` from `dichloroethane` (its SMILES is `CC(Cl)Cl`). Also, its `name_in_coolprop` is changed to `None` since `1,1-dichloroethane` is not available in CoolProp.
This commit does not actually impact any of the RMG simulations.
> Fixed minor error in the solvent library

- input/kinetics/families/Retroene/groups.py
- input/kinetics/families/Retroene/rules.py
- input/kinetics/families/Retroene/training/dictionary.txt
- input/kinetics/families/Retroene/training/reactions.py
This PR adds 3 training reactions to the retroene family. All calculations were done at `CCSD(T)-F12/cc-pVDZ-F12//ωB97X-D3/def2-TZVP`. The rate tree was then refit using Matt's notebook (#490).
The long description includes the indices that label these species in the dataset paper I'm working on. These indices can be used to find the raw log files from the QM calculations. 
Do we normally store the results from running [kinetics_library_to_training.ipynb](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/ipython/kinetics_library_to_training.ipynb) or the tree generation notebook somewhere on RMG server?
> Refit Retroene Rate Rules

- input/kinetics/families/2+2_cycloaddition/groups.py
- input/kinetics/families/Diels_alder_addition/groups.py
I found two families that have this problem. The one in `2+2_cycloaddition` was introduced by my old PR (oops). There could be more undiscovered bugs like these.
Currently, these pairs of reactants/products can be generated from the forward direction, but would encounter `UndeterminableKineticsError` while generated from the reverse direction. See below for example. This is caused by developer writing the head node in a way that hopes to avoid certain reactions from being generated. In these two families, the developer tried to avoid generating C=C + C=C cycloaddition in 2+2_cycloaddition and  avoiding double counting allene in Diels_alder_addition. This works fine when generating in the forward direction.
However, this would cause problem when generating from the reverse direction. Take …
> Use forbidden group instead of defining non-symmetric head node to avoid UndeterminableKineticsError

- input/kinetics/families/Retroene/training/reactions.py
- input/kinetics/families/ketoenol/groups.py
- input/kinetics/families/ketoenol/rules.py
- input/kinetics/families/ketoenol/training/dictionary.txt
- input/kinetics/families/ketoenol/training/reactions.py
This PR adds 3 training reactions to the keto-enol family. All calculations were done at `CCSD(T)-F12/cc-pVDZ-F12//ωB97X-D3/def2-TZVP`. The rate tree was then refit using Matt's notebook (#490).
The long description includes the indices that label these species in the dataset paper I'm working on. These indices can be used to find the raw log files from the QM calculations.
> Refit Ketoenol Rate Rules

- input/kinetics/libraries/Surface/CPOX_Pt/Deutschmann2006_adjusted/reactions.py
related to [this issue](https://github.com/ReactionMechanismGenerator/RMG-database/issues/517), I fixed a typo in the adjusted deutschmann library.
> fixing up a typo in the coverage dependence

- input/thermo/groups/group.py
- input/thermo/libraries/CHOBr_G4.py
We missed this molecule somehow, and the thermo estimate is really poor which is causing reverse rates to violate collision limit by many order of magnitude.
https://rmg.mit.edu/database/thermo/molecule/1%20O%20%20u0%20p2%20c0%20%7B2,D%7D%0A2%20C%20%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B4,S%7D%0A3%20Br%20u0%20p3%20c0%20%7B2,S%7D%0A4%20H%20%20u0%20p0%20c0%20%7B2,S%7D%0A
I calculated the molecule with G4 and added it to thermo library and thermo groups
> O=CHBr thermo

- input/thermo/libraries/surfaceThermoPt111.py
**Purpose:**
Adding thermochemistry for CO2, COOH, and HCOO to the Pt(111) database
**Method**
Thermochemistry based on DFT calculations using VASP with the RPBE exchange-correlation functional. 
Thermochemistry estimated from the energies with Katrin Blondals' method.
> Adding thermo for Pt111

- input/thermo/groups/adsorptionPt111.py
Vinyl only converged as bidentate on Pt111, so the current input is not consistent with the underlying geometry.
I commented it out for that reason, and since we already have bidentate vinyl in this library (index 48).
This change will have the result that adsorption corrections based on *CH3 data (C-*R3) will be used instead when C-*RCR2 adsorbates are proposed by RMG, which I think is preferred over using the data based on bidentate vinyl for that going forward (for now).
> Commented out the entry with index 57 (C-*RCR2) in adsorptionPt111.py

- input/kinetics/libraries/CurranPentane/dictionary.txt
- input/kinetics/libraries/CurranPentane/reactions.py
- input/thermo/libraries/CurranPentane.py
- trigger-rmg-tests.sh
Errors in label and structures for H2C3 isomers in the CurranPentane library are corrected:
- Previously omitted species H2CCC is added back
- C3H2 is updated to C#C[CH] from C=C=[C] (evolves from propargyl)
- All reactions for C3H2, C3H2(S), H2CCC(S), C3H2C (three-member ring) are checked and reassigned as needed
Closes #526
> Fix labels, structures, and reactions for C:3 H:2 species in CurranPentane

- input/transport/groups/nonring.py
- input/transport/groups/ring.py
The transport groups were previously missing nitrogen. The nitrogen groups for the transport GAV have been added to the RMG-database. Two nitrogen molecules have been added to the `transportTest.py`.
Note that this PR needs simultaneous update of RMG-Py and RMG-database. (Twin RMG-Py PR is: [ #2274](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2274))
Several nonring and ring nitrogen groups are added to `RMG-database/input/transport/groups/`.
These group values are obtained from Joback's Ph.D. thesis Table 3 and Table 13. These values can be also found [here](https://en.wikipedia.org/wiki/Joback_method#Critical_temperature). The nitrogen groups with any missing values were not added to the RMG-database. 
Two molecules with SMILES `CNC` and `c1ncc[nH]1` have been added to the …
> Add Nitrogen groups to transport 

- input/kinetics/families/1,3_sigmatropic_rearrangement/groups.py
- input/kinetics/families/1,3_sigmatropic_rearrangement/rules.py
- input/kinetics/families/1,3_sigmatropic_rearrangement/training/dictionary.txt
- input/kinetics/families/1,3_sigmatropic_rearrangement/training/reactions.py
- input/kinetics/families/Ketoenol/groups.py
- input/kinetics/families/Ketoenol/rules.py
- input/kinetics/families/Ketoenol/training/dictionary.txt
- input/kinetics/families/Ketoenol/training/reactions.py
- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
The previous PR (#550) added a thermo library for species involved in training reactions for the ketoenol and 1,3 sigmatropic rearrangement families. This current PR performed 1D rotor scans on the reactants and products to improve the estimations from the thermo library. Scans are also done on the TS to improve A-factors for the training reactions used to fit the rate trees.
> Rotor scans

- input/kinetics/families/Ketoenol/groups.py
- input/kinetics/families/Ketoenol/rules.py
- input/kinetics/families/Ketoenol/training/dictionary.txt
- input/kinetics/families/Ketoenol/training/reactions.py
- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
This PR adds 18 training reactions to the ketoenol family and refits the rate tree. All species are calculated at `CCSD(T)-F12a/cc-pVDZ-F12//ωB97X-D3/def2-TZVP`. A thorough conformer search was done with ACS on the reactant, TS, and product. 1D rotor scans were also done on the reactant, TS, and product. All scans start and end in the same place and have the lowest energy well at 0 degrees, which makes sense since a conformer search was done for each species. The notebook below has `assert glog.success` which was True for all species. 
[visualize_scans.ipynb.zip](https://github.com/ReactionMechanismGenerator/RMG-database/files/8307710/visualize_scans.ipynb.zip)
> More ketoenol training rxns

- input/kinetics/families/R_Recombination/training/reactions.py
The units for some of the R_Recombination training reactions are 'cm^3/(mole*s)' when they should be 'cm^3/(mol*s)'
This breaks the Arrhenius.to_cantera_kinetics() function because it is expecting one of:
```
rate_units_dimensionality = {'1/s': 0,
's^-1': 0,
'm^3/(mol*s)': 1,
'm^6/(mol^2*s)': 2,
'cm^3/(mol*s)': 1,
'cm^6/(mol^2*s)': 2,
'm^3/(molecule*s)': 1,
'm^6/(molecule^2*s)': 2,
'cm^3/(molecule*s)': 1,
'cm^6/(molecule^2*s)': 2,
}
```
These are the only instances of using 'cm^3/(mole*s)' I could find in any of the training reactions in the database, so I'm assuming it's a typo.
> Typo in R_Recombination training reaction units

- input/kinetics/families/Ketoenol/groups.py
- input/kinetics/families/Ketoenol/rules.py
- input/kinetics/families/Ketoenol/training/dictionary.txt
- input/kinetics/families/Ketoenol/training/reactions.py
- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
This PR adds 71 training reactions to the ketoenol family and refits the rate tree. Originally, there were only 6 training reactions. After this PR (as well #565 and #568), there are now just over 100 training reactions so our ketoenol rate estimates have gotten substantially better. All species were calculated at `CCSD(T)-F12a/cc-pVDZ-F12//ωB97X-D3/def2-TZVP`. A thorough conformer search was done with ACS on the reactant, TS, and product. 1D rotor scans were also done on the reactant, TS, and product. All scans start and end in the same place and have the lowest energy well at 0 degrees, which makes sense since a conformer search was done for each species. The notebook below has `assert glog.success` which was True for all species. Also included in the zip file is the notebook for …
> More ketoenol rxns

- input/kinetics/families/Ketoenol/groups.py
- input/kinetics/families/Ketoenol/rules.py
- input/kinetics/families/Ketoenol/training/dictionary.txt
- input/kinetics/families/Ketoenol/training/reactions.py
- input/kinetics/families/Retroene/groups.py
- input/kinetics/families/Retroene/rules.py
- input/kinetics/families/Retroene/training/dictionary.txt
- input/kinetics/families/Retroene/training/reactions.py
- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
This PR updates the values of retroene training reactions added in PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/523 by incorporating rotor scans and then refitting the rate tree. In general, the standard deviation of ln(k) is lower now after updating the values. All species were calculated at CCSD(T)-F12a/cc-pVDZ-F12//ωB97X-D3/def2-TZVP. A thorough conformer search was done with ACS on the reactant, TS, and product. 1D rotor scans were also done on the reactant, TS, and product. All scans start and end in the same place and have the lowest energy well at 0 degrees. The notebook below has assert glog.success which was True for all species. Also included in the zip file is the notebook for running ATG to refit the rate rules. This PR should be merged in after …
> Retroene rotor scans

- input/kinetics/families/1,3_sigmatropic_rearrangement/groups.py
- input/kinetics/families/1,3_sigmatropic_rearrangement/rules.py
- input/kinetics/families/Ketoenol/groups.py
- input/kinetics/families/Ketoenol/rules.py
- input/kinetics/families/Ketoenol/training/dictionary.txt
- input/kinetics/families/Ketoenol/training/reactions.py
- input/kinetics/families/Retroene/groups.py
- input/kinetics/families/Retroene/rules.py
- input/kinetics/families/Retroene/training/dictionary.txt
- input/kinetics/families/Retroene/training/reactions.py
- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
Previously, #565 added 1D rotor scans on the reactants and products to improve the estimations from the thermo library. Scans were also done on the TS to improve A-factors for the training reactions used to fit the rate trees. However, when using ATG, this previous PR used the following set of thermo libraries: `thermo_libraries = ['Spiekermann_refining_elementary_reactions', 'primaryThermoLibrary']`. However, our convention should be to use 
```
thermo_libraries = [
'Klippenstein_Glarborg2016', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo',
'primaryThermoLibrary', 'primaryNS', 'NitrogenCurran', 'NOx2018', 'FFCM1(-)',
'SulfurLibrary', 'SulfurGlarborgH2S', 'SABIC_aromatics',
],
```
and then append my thermo library to the front. This is the same list in our ATG …
> Refit 1,3 sigmatropic

- .github/workflows/CI.yml
I foolishly merged https://github.com/ReactionMechanismGenerator/RMG-database/pull/579 without removing the last commit that was only added for the twin RMG-Py and RMG-database PR. This PR reverts the github workflows back to what it should be i.e. checking out the main branch of RMG-Py.
> Set rmg py branch back to main

- input/kinetics/libraries/primaryH2O2/dictionary.txt
- input/kinetics/libraries/primaryH2O2/reactions.py
Added updated rate parameters for the H2O2 system that include ter-molecular reactions from two recent papers by Konnov.  https://doi.org/10.1016/j.combustflame.2015.07.014 and https://doi.org/10.1016/j.combustflame.2019.01.032. From 2015 and 2019 which should be more updated than the BurkeH2O2 2012 library. We named it primaryH2O2 with the intention to keep this library up to date rather than to make more replications on the literature citations. Excited species which currently are not supported by RMG were omitted. This PR only adds a kinetic library, for thermo properties users should still use the BurkeH2O2 library. We suggest to rename the BurkeH2O2 thermo library to primaryH2O2 to make it clearer for users.
> Added primaryH2O2 kinetic library

- input/kinetics/families/Diels_alder_addition/groups.py
- input/kinetics/families/Diels_alder_addition/rules.py
- input/kinetics/families/Diels_alder_addition/training/reactions.py
Following up on PR #582, training reaction 19 that I had added actually matches training reaction 0. Since reaction 0 was calculated from rate rules from 300 K to 1500 K, @hwpang and I agree that we should replace this duplicated reaction with the new value calculated at CCSD(T)-F12a/cc-pVDZ-F12//ωB97X-D3/def2-TZVP from 300 K to 2000 K. After replacing this reaction, I re-ran ATG to refit the rate rules. Doing so slightly decreased the median error from 6.14 to 5.95.
> Remove duplicate training reaction from diels alder

- input/thermo/libraries/surfaceThermoPt111.py
**Description**
This PR adds new thermo data for 33 adsorbates with more than 2 heavy atoms to the existing Pt111 database. The data is based on DFT calculations with the BEEF-vdW functional to make it consistent with the existing data. The thermo data for CO2*, HCOO*, and COOH* has been updated as well. A publication that include this data is in preparation. The heat of formation of CO2*, CO3*, and HCO3* was corrected since the BEEF-vdW functional leads to an overbinding of these adsorbates. 
**Review**
Check if the notation of the adsorbates is correct and the description of the DFT method in the label is sufficient.
> add Pt111 thermo data

- input/surface/libraries/metal.py
The metal.py file with the binding energies for the descriptor atoms on the various (111) and (211) facets used for the linear scaling relations does not contain information on the DFT method. An issue was raised (#592) reporting this. 
Katrin and I added a detailed description of the DFT method and settings, so the calculations can be reproduced by others. Please check if the information is correct or if something is missing.
> Update metal.py with DFT method

- input/kinetics/libraries/primaryH2O2/reactions.py
Several corrections were made for the primaryH2O2 kinetic library:
1. The collider efficiency for H2O was corrected in `O + H <=> OH`
2. The collider efficiency for O2 in `H2O <=> H + OH` was set to 0, since there's an updated rate for this reaction with O2 as a specific collider (rxn index 13)
3. Other minor rearrangements of reaction order so that similar reactions are grouped together for better human readability
> Corrections for primaryH2O2

- input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
In the Klippenstein_Glarborg2016 kinetic library, several singlet and triplet carbene reactions are wrongly lumped together. This PR fixes this issue. The problematic reactions are listed below
- CH4 + CH2 <=> CH3 + CH3
- CH2 + H2 <=> CH3 + H
- CH3 + CH2 = C2H4 + H
- CH2 + H <=> CH + H2
- CH2 + O <=> CO + H + H
- CH2 + OH <=> CH2O + H
- CH2 + CO2 <=> CO + CH2O
> Fix carbene chemistry in Klippenstein_Glarborg2016

- input/thermo/groups/group.py
Group `S6ddd` refers to a non-existing group called `S6ddd-XdXdXd`. It was now changed to the most generic group in this tree that has data, `S6ddd-OdXdXd`.
> Fix GAV S6ddd ref

- input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
- input/kinetics/libraries/NOx2018/reactions.py
- input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/reactions.py
Klippenstein_Glaborg_2016 and NOx_2018 CH3OH -> CH2(S) + H2O's low pressure k has been corrected. Also, T1 and T3 for Troe format have been corrected
> k_low and T1, T3 corrected for KLI_GLB_2016, NOx2018; PdepArrhenius info added for Nitrogen_GLB_JMZ

- input/kinetics/libraries/2003_Miller_Propargyl_Recomb_High_P/reactions.py
I got the following trace when simulating an RMG-genrated Chemkin file usng RMG's constant T/P reactor:
```
File "rmgpy/chemkin.pyx", line 945, in rmgpy.chemkin.load_chemkin_file
File "rmgpy/chemkin.pyx", line 972, in rmgpy.chemkin.load_chemkin_file
File "rmgpy/chemkin.pyx", line 1446, in rmgpy.chemkin.read_reactions_block
File "rmgpy/chemkin.pyx", line 1440, in rmgpy.chemkin.read_reactions_block
File "rmgpy/chemkin.pyx", line 716, in rmgpy.chemkin.read_reaction_comments
rmgpy.exceptions.ChemkinError: Unexpected species identifier CBS-QB3 encountered in flux pairs for reaction C6H6(272) <=> B(274).
```
RMG did not read the flux pair correctly, and for some reason read the following line which was taken from a library comment.
This is the reaction it errored on:
```
! Reaction index: …
```
> Removed a comment from 2003_Miller kin lib

- setup.py
This `v3.2.0` branch should be merged into `stable` (which is in pull request #590) and _then_ `stable` into `main`, so don't merge this PR when approved. It is just for comparison and review purposes because there are hundreds of commits being merged into stable and it is hard to see the release-specific changes by reviewing #590.
> RMG-database version 3.2.0 release for review

- .github/workflows/CI.yml
ci is currently failing to download reference results for regression testing because it also failing to _upload_ them. I'm not sure why, but I do know that it's working on RMG-Py, so I have modified the ci configuration file to work more like RMG-Py.
> Fix Regression Testing Issue by Simplifying CI to Match RMG-Py

- input/kinetics/families/Surface_Abstraction/training/dictionary.txt
- input/kinetics/families/Surface_Abstraction/training/reactions.py
**Issue**
The CI/build-and-test-linux is failing for the recent pull requests. This failure is caused by the Surface_Abstraction family and we get the following error message.
`Kinetics surface family Surface_Abstraction: entries can be used to generate rate rules? ... ERROR: Unable to dlopen(cxxpath) in parent!`
This PR is related to issue #632 
**Solution**
The reaction with index 39 in `reactions.py` was not correctly formatted, I think. After adjusting the format to match the other training reactions, I was able to run the `databaseTest` locally without any errors. Let's see if the `databaseTest` on Github works now, too.
> fix Surface_Abstraction training reactions format

- input/thermo/groups/adsorptionPt111.py
**Description**
I completely overhauled the adsorption correction database for Pt(111). The current adsorption corrections are based on the initial Pt(111) database create by Katrin (DOI:[10.1021/acs.iecr.9b01464](https://doi.org/10.1021/acs.iecr.9b01464)). I have updated the adsorption corrections to include all the adsorbates that I have added recently (DOI: [10.1021/acscatal.2c03378](https://doi.org/10.1021/acscatal.2c03378)). Additionally, I have revised the thermo tree for bidentate and included a new branch for bridged bidentate species. The new adsorption correction trees can be found in the SI of this paper DOI: [10.1002/anie.202306514](https://doi.org/10.1002/anie.202306514). Our previous adsorption correction for the enthalpy of formation for bidentate species was a simple …
> update adsorption corrections

- .github/workflows/CI.yml
- .github/workflows/conda_build.yml
- copy the download logic from RMG-Py (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2669) that updates the version of download-artifact
- increment setup-miniconda
Pair PR with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2669
> github actions CI maintainence

- scripts/fitThermoGroupsFromThermoLibrary.ipynb
In the `fitThermoGroupsFromThermoLibrary` script, an inifinite loop may occur when making missing groups. 
In particular, during the step where the code is searching for all child nodes that are subgraph isomorphic to a newly generated group, the function for isomorphic checks may misidentify two graphs as isomorphic even if their labeled atoms do not match. This will cause an inifinite loop where no matter how specific a newly generated group is, there will always be a child node that is subgraph isomorphic to it. This is resolved by turning the `generate_initial_map` option on.
> Fixed a potential infinite loop in the script for fitting Benson groups. 

- input/kinetics/libraries/C6H5_C4H4_Mebel/reactions.py
I got the following trace when simulating an RMG-genrated Chemkin file usng RMG's constant T/P reactor:
```ChemkinError                              Traceback (most recent call last)
[/tmp/ipykernel_1667806/515436996.py](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_1667806/515436996.py) in 
1 species, reactions = load_chemkin_file(path=chemkin_path,
----> 2                                        dictionary_path=dict_path
3                                       )
[~/Code/RMG-Py/rmgpy/chemkin.pyx](https://file+.vscode-resource.vscode-cdn.net/home/nelly/Code/scripts/NPS/~/Code/RMG-Py/rmgpy/chemkin.pyx) in rmgpy.chemkin.load_chemkin_file()
[~/Code/RMG-Py/rmgpy/chemkin.pyx](https://file+.vscode-resource.vscode-cdn.net/home/nelly/Code/scripts/NPS/~/Code/RMG-Py/rmgpy/chemkin.pyx) …
```
> removed rxns comments that started with the word fit

- input/forbiddenStructures.py
- input/kinetics/libraries/HydrazinePDep/reactions.py
- input/kinetics/libraries/primaryH2O2/reactions.py
- input/kinetics/libraries/primaryNitrogenLibrary/dictionary.txt
- input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
- input/thermo/libraries/NH3.py
- input/thermo/libraries/primaryNS.py
Added the `NH3` therno library based on CCSD(T)-F12/cc-pVTZ-F12//B2PLYPD3/aug-cc-pVTZ computations (enthalpies taken from ATcT where available)
Made significant modifications and additions to the kinetic `promaryNitrogenLibrary` based on updated literature and based on the submitted "NH3-1" paper
Also added several forbidden species and made two minor modifications to the `primaryNitrogenLibrary` kinetic library
We should still add PDep reactions calculated by us on the N2H3 surface, and later we expect to have updated reactions of the N2H4 surface.
Points for discussion:
- There are many non-phisical species in the H/N/O space (with legitimate Lewis structure and Molecule representation, but which do not exist, see [here](https://doi.org/10.1002/cphc.202200373)). Should we keep adding …
> NH3 thermo and kinetic data additions

- scripts/fitThermoGroupsFromThermoLibrary.ipynb
Currently the block checking for bad fits will repeatedly add the species index with bad fit if more than one criterion for bad fits is met. This makes the output cell very long if there are multiple "bad fit species". This PR removes the duplicates as well as providing feedback on how many species out of the library have bad fits.
> Removes duplicate bad fits in the Benson Group Fitting Notebook

- .github/workflows/CI.yml
Matches the corresponding PR on RMG-Py.
> Changes to CI to match RMG-Py

- input/thermo/groups/adsorptionPt111.py
**Description**
The nodes in the adsorption correction file adsorptionPt111.py were rather restrictive. In most nodes it was specified that the general`R` cannot have lone pairs `p0`. I didn't pay close attention to this when I restructured the adsorption correction database because the `R` was mostly C in the training data. However, this is not correct. In most cases, the R can also be replaced with O/N. Actually, in some cases the training data that I used contained O, but the node would not have been used to estimate the thermo for this species. @kirkbadger18 caught this detail. 
I revised now the adjacency lists and made the nodes more permissive, by changing the `p0` to `px` whenever it is reasonable. 
I did not touch the nodes containing nitrogen, because @kirkbadger18 is doing a …
> make adsorptionPt111 more flexible with lone pairs px

- input/kinetics/libraries/primaryH2O2/reactions.py
These reactions were marked as irreversible in the original manuscript, but were added to the `primaryH2O2` library as reversible. They should be insignificant at the conditions reported in 10.1016/j.combustflame.2015.07.014, and including them as reversible is incorrect.
>  fixed irreversible reactions from table 2 of Konnov 2015, X2 and X3

- .github/workflows/CI.yml
Artifact upload v3 will stop working in a few weeks - Jan 31st. (#673)
This PR makes the small change to update to v4.
> Update CI artifact actions to v4

- input/kinetics/families/Surface_Dissociation_vdW/groups.py
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2764
RMG crashed from an AtomType Error from trying to apply the Surface_Dissociation_vdW template to various species containing N+ in the 1* or 2* template label location.
I don't know if there's some deeper issue with how RMG handles bond breaking and updating the charge on N, but this is one possible fix/bandaid. It forbids any species that has N+ (charged nitrogen) in the 1* or 2* label positions.
> Forbid charged nitrogen species from breaking to prevent AtomType error on N++ species

- input/thermo/libraries/Elliott_OOQOOH.py
Added the thermo entries from Elliott's paper on OOQOOH radicals:
Elliott SN, Mulvihill CR, Ghosh MK, Curran HJ, Klippenstein SJ. Systematic exploration of the thermochemistry for a set of peroxy hydroperoxy-alkyl radicals. Proceedings of the Combustion Institute. 2024;40(1-4):105618-. doi:10.1016/j.proci.2024.105618 [https://doi.org/10.1016/j.proci.2024.105618](https://doi.org/10.1016/j.proci.2024.105618)
Here's my script for generating the database:
[make_elliot_lib.txt](https://github.com/user-attachments/files/19573091/make_elliot_lib.txt)
For testings, I will 
[x] run an RMG mechanism with it -- tried adding it to my butane input file and it does fine
[x] check the values against group additivity. -- looks good
Ready for review!
> Add thermo entries from Elliott OOQOOH paper

- .github/workflows/CI.yml
When we updated `RMG-Py` to Python 3.9, we forgot to update the CI for `RMG-Database`.  So CI has been failing for the past 3 weeks.
This PR simply updates the installed Python to 3.9; changes Julia install to the current supported install; and changes `python-jl` back to `python`.
> Fix failing CI due to Python 3.9 changes

- input/surface/libraries/metal.py
Add the Fe110 facet to RMG's database.
Values taken from:
Xu L, Kirvassilis D, Bai Y, Mavrikakis M. Atomic and molecular adsorption on Fe(110).
Surface science. 2018;667:54-65. doi:10.1016/j.susc.2017.09.002
The lattice constant PW91 is given in the paper as a=2.85 Angstrom.
Then surface site density was calculated using the following code
```
import ase.build
import numpy as np
import ase.visualize
import rmgpy.constants
a = 2.85  # A
surface = ase.build.bcc110("Fe", (3, 3, 3), a=a, periodic=True)
a1 = surface.cell[0]
a2 = surface.cell[1]
unit_cell_area = np.linalg.norm(np.cross(a1, a2))
print(f'Unit cell area:\t{area:0.5f}\tA^2')
site_area = unit_cell_area / 9.0
print(f'Site area:\t{site_area:0.5f}\t\tA^2/site')
print(f'Site density:\t{1.0 / site_area:0.5f}\t\tsites/A^2')
SDEN = 1.0 / …
```
> Add Fe110 to metal database
