- .travis.yml
- input/kinetics/families/SubstitutionS/groups.py
- input/kinetics/families/intra_substitutionCS_cyclization/groups.py
- input/kinetics/families/intra_substitutionCS_cyclization/rules.py
- input/kinetics/libraries/Sulfur/DTBS/dictionary.txt
- input/kinetics/libraries/Sulfur/DTBS/reactions.py
A few changes I made in order to fix errors that arose with the di-tert-butyl sulfide model as well as the seed mechanism used.
Changes involve minor restructuring of radical trees for SubstitutionS and intra_substitutionCS_cyclization. Changes were based on how the radical trees in H_abstraction and Disproportionation are currently structured.
The seed mechanism was created by Caleb, most likely from his own quantum calculations, although it was not clearly documented.
These changes should be sufficient to make the DTBS model readily reproducible without errors.
> Changes to database for DTBS model

- input/kinetics/libraries/C10H11/dictionary.txt
- input/kinetics/libraries/C10H11/reactions.py
- input/kinetics/libraries/C3/dictionary.txt
- input/kinetics/libraries/C3/reactions.py
- input/kinetics/libraries/Fulvene_H/dictionary.txt
- input/kinetics/libraries/Fulvene_H/reactions.py
- input/kinetics/libraries/naphthalene_H/dictionary.txt
- input/kinetics/libraries/naphthalene_H/reactions.py
- input/kinetics/libraries/vinylCPD_H/dictionary.txt
- input/kinetics/libraries/vinylCPD_H/reactions.py
- input/thermo/libraries/C10H11.py
- input/thermo/libraries/C3.py
- input/thermo/libraries/Fulvene_H.py
- input/thermo/libraries/naphthalene_H.py
- input/thermo/libraries/vinylCPD_H.py
From Aäron G. Vandeputte, Shamel S. Merchant, Marko R. Djokic, Kevin M. Van Geem, 
Guy B. Marin, William H. Green, "Detailed study of cyclopentadiene pyrolysis in the 
presence of ethene: realistic pathways from C5H5 to naphthalene." (2016)
> Add Cyclopentadiene pyrolysis thermo and kinetics libraries

- input/solvation/libraries/solvent.py
I added SMILES for all the solvents. This will allow RMG liquid phase reactions to recognize the solvent by its molecular structure.
In order for this commit to pass all the tests, the RMG-Py must be updated with my new code in my latest RMG-Py pull request.
Could someone check my RMG-Py pull request first? If that can be merged, could someone check and merge this? 
Thank you!
> added solvent SMILES representation

- .travis.yml
Corresponding to latest change by https://github.com/ReactionMechanismGenerator/RMG-Py/pull/697
> Travis: create anaconda environment using environment_linux.yml

- input/kinetics/libraries/Chernov/dictionary.txt
- input/kinetics/libraries/Chernov/reactions.py
- input/kinetics/libraries/Narayanaswamy/dictionary.txt
- input/kinetics/libraries/Narayanaswamy/reactions.py
- input/kinetics/libraries/fascella/dictionary.txt
- input/kinetics/libraries/fascella/reactions.py
- input/kinetics/libraries/kislovB/dictionary.txt
- input/kinetics/libraries/kislovB/reactions.py
- input/thermo/libraries/Chernov.py
- input/thermo/libraries/Narayanaswamy.py
Adding four aromatic libraries from literature:
1. Fascella
2. Kislov
3. Chernov
4. Narayanaswamy
> Aromatic libraries

- input/kinetics/libraries/JetSurF0.2/dictionary.txt
- input/kinetics/libraries/JetSurF0.2/reactions.py
- input/thermo/libraries/JetSurF0.2.py
A detailed chemical reaction model for the combustion of jet-fuel surrogate,
http://web.stanford.edu/group/haiwanglab/JetSurF/JetSurF2.0/index.html
> Added the JetSurF 0.2 RMG kinetic & thermo library

- input/kinetics/libraries/2001_Tokmakov_H_Toluene_to_CH3_Benzene/dictionary.txt
- input/kinetics/libraries/2001_Tokmakov_H_Toluene_to_CH3_Benzene/reactions.py
- input/kinetics/libraries/C6H5_C4H4_Mebel/dictionary.txt
- input/kinetics/libraries/C6H5_C4H4_Mebel/reactions.py
- input/kinetics/libraries/Mebel_C6H5_C2H2/dictionary.txt
- input/kinetics/libraries/Mebel_C6H5_C2H2/reactions.py
- input/kinetics/libraries/Mebel_Naphthyl/dictionary.txt
- input/kinetics/libraries/Mebel_Naphthyl/reactions.py
- input/kinetics/libraries/c-C5H5_CH3_Sharma/dictionary.txt
- input/kinetics/libraries/c-C5H5_CH3_Sharma/reactions.py
These are the aromatic libraries for the C6H5+C2H2 and C6H4C2H+C2H2 Potential Energy Surfaces.
> Pull request for aromatic libraries C6H5+C2H2 and C6H4C2H+C2H2

- input/thermo/groups/group.py
- input/thermo/groups/radical.py
Added many new thermo groups and HBI corrections from Paraskevas et al 2013
> Oxygenate benson groups

- input/thermo/groups/polycyclic.py
This PR tends to lay foundation for more generalized polycyclic corrections. This change will provide heteropolycyclic species with base-line corrections calculated from hydrocarbon polycyclic species.
Once we have more heteropolycyclic data ready, more specific leaves can be created under these generic nodes.
> Generalize polycyclic correction for heteropolycyclics

- input/kinetics/families/1,2_Insertion_CO/groups.py
- input/kinetics/families/1,2_Insertion_CO/rules.py
- input/kinetics/families/1,3_Insertion_ROR/groups.py
- input/kinetics/families/1,3_Insertion_RSR/groups.py
- input/kinetics/families/1,4_Cyclic_birad_scission/groups.py
- input/kinetics/families/1,4_Linear_birad_scission/groups.py
- input/kinetics/families/Disproportionation/groups.py
- input/kinetics/families/Disproportionation/rules.py
- input/kinetics/families/Disproportionation/training/dictionary.txt
- input/kinetics/families/Disproportionation/training/reactions.py
- input/kinetics/families/H_Abstraction/groups.py
- input/kinetics/families/H_Abstraction/rules.py
- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/R_Addition_COm/groups.py
- input/kinetics/families/R_Addition_CSm/groups.py
- input/kinetics/families/R_Addition_MultipleBond/groups.py
- input/kinetics/families/SubstitutionS/groups.py
- input/kinetics/families/Substitution_O/groups.py
- testing/databaseTest.py
This pull request fixes entry accessibility problems in bimolecular families.
> Bimol accessibility

- meta.yaml
- setup.py
This PR adds necessary modifications for database v2.1.0 release.
> RMG-database v2.1.0 release

- input/forbiddenStructures.py
since now CH doublet is the agreed ground state, we should remove it from forbidden structure list.
> remove the forbidden structure of CH

- input/forbiddenStructures.py
- input/kinetics/families/1+2_Cycloaddition/groups.py
- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/R_Addition_MultipleBond/groups.py
- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- input/kinetics/families/R_Recombination/groups.py
- input/kinetics/families/R_Recombination/rules.py
- input/kinetics/families/R_Recombination/training/dictionary.txt
- input/kinetics/families/R_Recombination/training/reactions.py
- input/kinetics/families/intra_substitutionS_isomerization/groups.py
- input/kinetics/families/lone_electron_pair_bond/groups.py
- input/kinetics/libraries/Ethylamine/dictionary.txt
- input/kinetics/libraries/Ethylamine/reactions.py
- input/thermo/groups/group.py
- input/thermo/groups/radical.py
- input/thermo/groups/ring.py
- input/thermo/libraries/primaryThermoLibrary.py
This PR should be merged together with RMG-Py/nitrogen's PR (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/888) to be functional.
It includes:
- nitrogen thermo groups
- nitrogen radical thermo corrections
- various training reactions
- The ethylamine library
- ring corrections to account for heteroatoms.
- UN-forbidding previously forbidden groups. @nyee, let's discuss this
The temporary branch change commit in .travis.yml should be deleted before merging into master
> RMG-database/nitrogen's PR

- input/kinetics/families/intra_H_migration/rules.py
Change their rate to be per hydrogen, which means the degeneracy is considered
> Correct the rate rule of intra-H-migration based on J.Phys.Chem.A. Vol.114 No.18 2010 Sharma and Sumathy

- .travis.yml
This PR adds thermo central database authentication info for RMG-database travis testing.
> adds TCD authentication info for RMG-database test

- input/kinetics/families/Birad_R_Recombination/training/reactions.py
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/R_Recombination/rules.py
- input/kinetics/families/R_Recombination/training/reactions.py
- input/kinetics/libraries/BurkeH2O2inArHe/reactions.py
- input/kinetics/libraries/BurkeH2O2inN2/reactions.py
- input/kinetics/libraries/C10H11/reactions.py
- input/kinetics/libraries/C3/reactions.py
- input/kinetics/libraries/Ethylamine/reactions.py
- input/kinetics/libraries/Fulvene_H/reactions.py
- input/kinetics/libraries/JetSurF2.0/reactions.py
- input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/reactions.py
- input/kinetics/libraries/Nitrogen_Glarborg_Lucassen_et_al/reactions.py
- input/kinetics/libraries/Nitrogen_Glarborg_Zhang_et_al/reactions.py
- input/kinetics/libraries/naphthalene_H/reactions.py
- input/kinetics/libraries/vinylCPD_H/reactions.py
- input/thermo/libraries/BurkeH2O2.py
- input/thermo/libraries/C10H11.py
- input/thermo/libraries/C3.py
- input/thermo/libraries/Fulvene_H.py
- input/thermo/libraries/NitrogenCurran.py
- input/thermo/libraries/naphthalene_H.py
- input/thermo/libraries/vinylCPD_H.py
should solve https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1144
> Replace non-ASCII chars

- input/kinetics/libraries/Klippenstein_Glarborg2016/dictionary.txt
- input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
- input/thermo/libraries/FFCM1(-).py
- input/thermo/libraries/Klippenstein_Glarborg2016.py
for methane oxidation at high pressures and intermediate temperatures.
Taken from:
"High-pressure oxydation of methane"
Hamid Hashemi, Jakob M. Christensen, Sander Gersen, Howard Levinsky, Stephen J. Klippenstein, Peter Glarborg
Combustion and Flame 172, 2016, 349-364
http://dx.doi.org/10.1016/j.combustflame.2016.07.016
Also added a minor AdjList correction to FFCM1(-)
> Added the Klippenstein_Glarborg2016 thermo & kinetic libraries

- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
This PR adds some training reactions as in the title taken from
Siddique et al.'s [Hydrogen Abstraction from Hydrocarbons by NH2](http://pubs.acs.org/doi/abs/10.1021/acs.jpca.6b12890) 2017 paper
> Added H_Abs training reactions involving NH2 rad

- input/kinetics/families/ketoenol/groups.py
- input/kinetics/families/ketoenol/rules.py
We only have reasonable estimates for R1=R2OH = HR1R2=O and not for R1=R2OR4 = HR1R2=O this pull request adds estimates for those rates based Prof. Green's estimates and sets nodalDistances so that when R4 != H those estimates will be used.
> Ketoenol R4 != H

- .travis.yml
Equivalent to ReactionMechanismGenerator/RMG-Py#1255.
> Fix issues with Travis

- input/kinetics/families/1,2-Birad_to_alkene/rules.py
Imported from [RMG-Java](https://github.com/ReactionMechanismGenerator/RMG-Java/blob/master/databases/RMG_database/kinetics_groups/1%2C2-Birad_to_alkene/rateLibrary.txt)
Solves #231
> Added a description to the 1,2-Birad_to_alkene Family

- input/thermo/groups/group.py
- input/thermo/groups/radical.py
Addresses https://github.com/ReactionMechanismGenerator/RMG-Py/issues/385
Estimating thermo on master:
```
! Thermo group additivity estimation: group(O2s-CsCs)
O(S)(2)                 O   1               G   100.000  5000.000 3802.52      1
2.49999989E+00 1.04239305E-10-3.81844923E-14 6.18592324E-18-3.73869494E-22    2
-1.26038407E+04-9.59902267E+00 2.50000000E+00 2.64612706E-14-3.72536449E-17    3
1.71920118E-20-2.44483017E-24-1.26038408E+04-9.59902333E+00                   4
! Thermo group additivity estimation: group(S2s-CsCs)
S(S)(4)                 S   1               G   100.000  5000.000 3802.52      1
2.49999989E+00 1.04239305E-10-3.81844923E-14 6.18592324E-18-3.73869494E-22    2
4.99672848E+03-7.33856885E+00 2.50000000E+00 2.64612706E-14-3.72536449E-17    3 …
```
> Relocated singlets GAV from radical to group

- input/thermo/libraries/Lai_Hexylbenzene.py
Two groups of species in this library had previously swapped thermochemistry
The two groups are ToluenePlusH and ToluenePlusCH3
The thermochemistry of these two groups have been correctly assigned
> Changed thermo of species in Lai_Hexylbenzene.py

- input/kinetics/families/Birad_R_Recombination/training/dictionary.txt
- input/kinetics/families/Birad_R_Recombination/training/reactions.py
Poor estimation for this rate seems to be rooted in the fact that we can't estimate thermo well for HSOO and HSO in the training reaction used
for this rate originally
I have commented that rate out until we can estimate the thermo well and added a new rate from the literature for a more similar reaction
> Fix [O] - O bond scission rate

- input/kinetics/families/R_Addition_COm/groups.py
This is relevant to the pull request for RMG-Py debug_CO_update. There is only one modification on the recipe of family "R_Addition_COm", where the sequence of CHANGE_BOND and GAIN_PAIR has been changed.
> Modify the recipe for R_Addition_COm to make it reasonable

- .travis.yml
- input/kinetics/families/Intra_R_Add_Exocyclic/groups.py
- setup.py
This merges the release branch back into master so that it also contains the changes made on the release branch.
Changes:
- Version number increment
- Fix typo in forbidden structures of Intra_R_Add_Exocyclic
- New Travis build setup
> RMG-database v2.2.0 changes

- input/kinetics/libraries/FFCM1(-)/reactions.py
- input/kinetics/libraries/GRI-Mech3.0-N/reactions.py
- input/kinetics/libraries/GRI-Mech3.0/reactions.py
- input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
- input/kinetics/libraries/N-S_interactions/reactions.py
- input/kinetics/libraries/NOx2018/reactions.py
- input/kinetics/libraries/Sulfur/DMDS/reactions.py
- input/kinetics/libraries/Sulfur/DMS/reactions.py
- input/kinetics/libraries/Sulfur/DTBS/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgBozzelli/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgH2S/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgMarshall/reactions.py
- input/kinetics/libraries/Sulfur/GlarborgNS/reactions.py
So they can participate in p-dep networks
> Added the `elementary_high_p` flag to various kinetic libraries

- input/solvation/libraries/solute.py
Solves ReactionMechanismGenerator/RMG-Py#1479 by adding the McGowan volumes for He, Ne, and Ar in the database. Really small PR, should be able to merge fast.
> Add McGowan volumes for noble gases

- input/kinetics/families/1,2_shiftC/groups.py
- input/kinetics/families/1,2_shiftC/training/dictionary.txt
- input/kinetics/families/1,2_shiftC/training/reactions.py
- input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
- input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
- input/kinetics/families/Intra_R_Add_Exocyclic/groups.py
- input/kinetics/families/Intra_R_Add_Exocyclic/training/dictionary.txt
- input/kinetics/families/Intra_R_Add_Exocyclic/training/reactions.py
- input/kinetics/families/Intra_ene_reaction/groups.py
- input/kinetics/families/Intra_ene_reaction/training/dictionary.txt
- input/kinetics/families/Intra_ene_reaction/training/reactions.py
- input/kinetics/families/R_Addition_COm/training/dictionary.txt
- input/kinetics/families/R_Addition_COm/training/reactions.py
- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- input/kinetics/families/R_Recombination/training/dictionary.txt
- input/kinetics/families/R_Recombination/training/reactions.py
- input/kinetics/families/intra_H_migration/groups.py
- input/kinetics/families/intra_H_migration/training/dictionary.txt
- input/kinetics/families/intra_H_migration/training/reactions.py
- input/thermo/libraries/CBS_QB3_1dHR.py
- input/thermo/libraries/Narayanaswamy.py
Commits for rich-methane modeling paper, training reactions on C6H5+O2, C7H5 PES, and others. Also, so typos in existing libraries and training reactions are corrected.
> Aromatics 2018 dec

- input/thermo/groups/ring.py
The thermo parameters of ring(12dioxetane) were fitted by Hao-Wei Pang in May 2019 using CBS-QB3 calculations for oxygen-butadiene polymerization from Duminda Ranasinghe in April 2019.
> The thermo parameters of ring(12dioxetane) fitted with CBS-QB3 calculation results

- setup.py
Primarily just incrementing the version number.
> v2.4.0 release changes

- .travis.yml
> Install Q2DTor when running travis

- .conda/meta.yaml
- setup.py
Updates the database to python 3 as far as building the conda package is concerned.
> Py3 update

- input/kinetics/families/H_Abstraction/groups.py
- input/kinetics/families/H_Abstraction/training/dictionary.txt
- input/kinetics/families/H_Abstraction/training/reactions.py
- input/kinetics/libraries/Iodine-R_recombination/dictionary.txt
- input/kinetics/libraries/Iodine-R_recombination/reactions.py
- input/thermo/groups/group.py
- input/thermo/libraries/iodinated_Hydrocarbons.py
This PR is for the thermodynamics and kinetic data related to iodine chemistry 
H-abstraction and R_recombination were added
> Iodine database

- input/solvation/libraries/solvent.py
1. Add MeOH, MeOH:Water (50:50), Acetonitrile:Water(40:60, 60:40)
abraham solvent parameters to solvent.py
2. Add a citation section at the bottom of solvent.py for future
reference
> Add new abraham parameters for pure solvents and co-solvents

- input/thermo/libraries/thermo_DFT_CCSDTF12_BAC.py
Added thermo for cyanoisopropanol and methanediol
Should (hopefully) be a quick review
> Added CCSD(T)F12/DFT thermo for cyanoisopropanol, methanediol, and iC3H6CNOO

- input/reference_sets/main/Benzylide.yml
- input/reference_sets/main/Ethynol anion.yml
- input/reference_sets/main/Formyl anion.yml
- input/reference_sets/main/Methanide.yml
- input/reference_sets/main/Vinoxide.yml
- input/reference_sets/main/Vinyl anion.yml
This PR contains only the first commit of #404 to get the species corrections in
> Fix species information for select reference species

- input/reference_sets/main/12-Propadienyl anion.yml
- input/reference_sets/main/2-Propynylidyne.yml
- input/reference_sets/main/Chloromethylene.yml
- input/reference_sets/main/Dichloromethylene.yml
- input/reference_sets/main/Difluoromethylene.yml
- input/reference_sets/main/Ethylidyne.yml
- input/reference_sets/main/Fluoromethylene.yml
- input/reference_sets/main/Fluoromethylidyne.yml
- input/reference_sets/main/Formaldehyde cation.yml
- input/reference_sets/main/Hydroxymethylene.yml
- input/reference_sets/main/Propadienylidene.yml
- input/reference_sets/main/Vinylidene.yml
Additional reference species with the incorrect species information (e.g. adjacency lists)
> Fix species information errors for species 151 and 61

- input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
- input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
Calculations done at CCSD(T)/aug-cc-pVTZ//wB97xd/def2TZVP
> Added CH2OH + HCN training reactions to R_Add_Multiple_Bond

- input/kinetics/libraries/Surface/Nitrogen/dictionary.txt
- input/kinetics/libraries/Surface/Nitrogen/reactions.py
These came from Micro-kinetic modeling of NH3 decomposition on Ni and
its application to solid oxide fuel cells
From Deutschmann et al
doi: 10.1016/j.ces.2011.07.007
This the same as #388, but changed the branch name so the rmg-tests will pass
> Adding a nitrogen surface reaction library

- input/kinetics/families/Surface_Abstraction_vdW/groups.py
- input/kinetics/families/Surface_Addition_Single_vdW/groups.py
- input/kinetics/families/Surface_Adsorption_Abstraction_vdW/groups.py
- input/kinetics/families/Surface_Dissociation_Double_vdW/groups.py
- input/kinetics/families/Surface_Dissociation_vdW/groups.py
- input/kinetics/families/Surface_Dual_Adsorption_vdW/groups.py
- input/kinetics/families/Surface_vdW_to_Bidentate/groups.py
this PR goes with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2062
Change the `FORM_BOND` action to `CHANGE_BOND` actions in vdW families
> vdW families change_bond action

- input/transport/groups/nonring.py
- input/transport/libraries/NIST_Fluorine.py
Added NIST transport library for fluorines and added new halogen transport groups
> Halogens transport

- input/transport/groups/nonring.py
- input/transport/libraries/NIST_Fluorine.py
***
Previously there weren't any libraries that involved more deeply the hydrogen combustion mechanism. Konnov proposes in two papers a more elaborated reaction mechanism. This pull request will add a library including this more elaborated hydrogen combustion mechanism and updated reactions.
The major change include:
* 1. The addition of a reactions.py and directory.txt files including 46 reactions and 12 species respectively. 
This library has been tested with the current master branch of RMG and reaches a final solution without errors.
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-database/files/6429556/dictionary.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-database/files/6429557/reactions.txt)
> H2O2 Konnov library

- input/thermo/libraries/primaryThermoLibrary.py
This PRs added some key species to primaryThermoLibrary
simultaneous with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2123
> Primary thermo library additions

- input/thermo/groups/adsorptionPt111.py
Twin with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2169
Adds labels to the `adsorptionPt111` tree
> Adsorption labels - twin PR

- input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
- input/kinetics/families/Surface_Addition_Single_vdW/training/reactions.py
- input/kinetics/families/Surface_Adsorption_Abstraction_vdW/training/reactions.py
- input/kinetics/families/Surface_Adsorption_Dissociative/training/reactions.py
- input/kinetics/families/Surface_Dissociation/training/reactions.py
- input/kinetics/families/Surface_Dissociation_Beta/training/reactions.py
- input/kinetics/families/Surface_Dissociation_Double_vdW/training/reactions.py
- input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
- input/kinetics/families/Surface_Migration/training/reactions.py
We found some errors in the training reactions for surface families.
This PR goes through each surface family and double checks the kinetics
> Surface training reactions fixups

- input/kinetics/families/Surface_Adsorption_Double/groups.py
- input/kinetics/families/Surface_Adsorption_Single/groups.py
- input/kinetics/families/Surface_Adsorption_vdW/groups.py
- input/kinetics/families/Surface_Dissociation/groups.py
- input/kinetics/families/Surface_Dissociation_Beta/groups.py
- **Purpose**:
Adding more nodes in some kinetics families tree for training data
- **Description**:
A separated PR from #479 
Separating previous one into three PRs: "adding libraries", "adding tree nodes", and "adding training data"
> Adding more nodes in some kinetics families tree

- input/thermo/groups/adsorptionPt111.py
- input/thermo/libraries/primaryThermoLibrary.py
vdW adsorbed species were using nitrogen thermo which was throwing some stuff off. I also added thermo for C(Q).
> Adding in some more thermo to the database

- input/statmech/groups/groups.py
- input/statmech/libraries/halogens_G4.py
Added statmech library and groups for halogens.
Simultaneous with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2195
The new statmech groups are more accurate at estimating the partition function at 1000k for halogenated species.  The MAE is reduced from 3 to 1 (2 orders of magnitude better).
> Halogens pdep

- scripts/AEC_procedure.ipynb
- scripts/BAC_procedure.ipynb
This PR adds notebooks that demonstrate how to add/update AEC and BAC values in RMG-database. Thank you to Mark and Oscar for contributing to the BAC notebook.
> AEC BAC notebooks

- input/thermo/libraries/Spiekermann_refining_elementary_reactions.py
My paper had not been published yet when I started this thermo library. Now that the paper is published, I updated the citation in the file.
> Update citation for Sci Data paper in thermo library

- input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
Update of rate coefficients for several reactions using new parameters by Glarborg et al. (2021) and Sarathy et al. (2022). Also, addition of new reactions.
> Updated reactions for Primary nitrogen library

- input/kinetics/libraries/primaryNitrogenLibrary/dictionary.txt
- input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
Some modifications and additions to the primary nitrogen library:
- Corrected Sarathy2022 rates
- Added Lin2003d rates
- Corrected the NNH + O2 <=> N2 + HO2 rate from Miller2011
- Added Dievart2020 rates
- Minor style modifications
> Updates to the primaryNitrogenLibrary

- .github/workflows/conda_build.yml
- setup.py
These are the commits missing from the last release: version 3.1.0
> Stable2main

- input/solvation/groups/group.py
- input/solvation/groups/halogen.py
- input/solvation/groups/longDistanceInteraction_cyclic.py
- input/solvation/groups/longDistanceInteraction_noncyclic.py
- input/solvation/groups/polycyclic.py
- input/solvation/groups/ring.py
- input/solvation/libraries/solvent.py
This PR updates the group additivity and Abraham parameter fitting citations to point to Yunsie's paper in 2022.
_Edit_: The commits on March 20th also include edits to the viscosity parameters to fix erroneous values.
> Update solvent data: (1) fix erroneous viscosities (2) update manuscript citations

- input/transport/groups/nonring.py
- input/transport/groups/ring.py
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2569 - not sure if this is exactly what was intended, or if these need to be changed throughout the database.
> Critical Pressure Estimation Bug Fix

- input/kinetics/libraries/primaryNitrogenLibrary/dictionary.txt
- input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
Added PDep rate coefficients on the N2H3 PES taken from Keslin et al. 2024 to the `primaryNitrogenLibrary`
> Added PDep rates on the N2H3 PES to the PNL

- scripts/AEC_procedure.ipynb
The "output_file" key is no longer available
> changed input name in aec.excecute

- input/quantum_corrections/data.py
Add atomic energies at the LOT of CCSD(T)-F12/Aug-cc-pVTZ-F12.
> Update of ccsd(t)f12/augccpvtzf12
